/**
 * Every word in the patient app sample, in both languages. A design sample is
 * drawn in Arabic from the start, not translated after it is approved.
 */
export type Lang = "en" | "ar";

const en = {
    evening: "Good evening, Mariam",
    arriving: "How are you arriving today?",
    moods: { calm: "Calm", anxious: "Anxious", low: "Low", sleep: "Can't sleep" },
    moodNote: {
      calm: "Good to hear. A short exercise might keep it that way.",
      anxious: "You don't have to wait for Thursday. Someone can talk now.",
      low: "Thank you for saying so. Someone can talk now, or you can write it down first.",
      sleep: "Sleep is the most common thing people come here with. Here's who can help.",
    },
    freeNow: "therapists free now",
    talkNow: "Talk to someone now",
    heroTitle: "Someone can listen in minutes",
    search: "Search therapists, topics, languages",
    topics: "Topics",
    topicNames: { anxiety: "Anxiety", sleep: "Sleep", relationships: "Relationships", grief: "Grief", stress: "Work stress", family: "Family" },
    availableNow: "Free now",
    seeAll: "See all",
    nextSession: "Your next session",
    inDays: "in 2 days",
    exercises: "Two minutes for you",
    breathe: "Breathe with the circle",
    breatheIn: "In",
    breatheOut: "Out",
    ground: "5 things you can see",
    yourRecord: "Your record",
    recordLine: "2 summaries by 2 therapists. You decide who reads them.",
    asking: "1 person is asking to read it",
    youPay: "You pay",
    covers: "Habiba Holdings pays 60%",
    start: "Start",
    results: "therapists",
    filters: { now: "Free now", arabic: "Arabic", english: "English", under30: "Under $35 for you", women: "Women" },
    noResults: "Nobody matches all of that. Try removing a filter.",
    verified: "Verified",
    years: "years",
    reliability: "turned up",
    of: "of",
    sessions: "sessions",
    about: "About",
    specialities: "Works with",
    times: "Or pick a time",
    today: "Today",
    tomorrow: "Tomorrow",
    startNow: "Start now",
    bookingTitle: "Start with",
    length: "How long",
    min30: "30 min",
    min60: "60 min",
    session: "Session",
    vat: "VAT 14% on your share",
    payWith: "Pay with",
    card: "Card",
    cardNote: "In the room within seconds",
    transfer: "Bank transfer",
    transferNote: "A person checks it, usually minutes",
    startAndPay: "Start and pay",
    held: "held for you",
    consentTitle: "May Sara's notes be written from a recording?",
    consentBody: "Yes, and a draft note is written from the session. Sara reads and signs it before you see anything. You can stop the recording at any moment.",
    yes: "Yes, you may record",
    no: "No, do not record",
    either: "The session goes ahead either way.",
    goIn: "Go in",
    recording: "Recording",
    notRecording: "Not recording",
    stopRecording: "Stop recording",
    stopped: "Recording stopped. Nothing from now on is kept.",
    end: "End",
    minimise: "Minimise",
    stillWriting: "Sara is still writing your summary",
    stillWritingBody: "Nothing written by a machine reaches you until she has read and signed it.",
    signed: "Signed by",
    psychologist: "Clinical psychologist",
    summary:
      "We talked about waking at 4am and the wind-down routine you kept on four nights. The breathing exercise helped on Tuesday. Next: keep the routine for another week.",
    nextStep: "Your next step",
    nextStepBody: "Phone away an hour before bed, four nights this week.",
    whoReads: "Who can read your record",
    canRead: "Can read",
    askingNow: "Asking now",
    yes24: "Yes, for 24 hours",
    yesUntil: "Until I change my mind",
    noThanks: "No",
    granted: "Dr Kareem can read your summaries for 24 hours.",
    stop: "Stop",
    benefit: "Your benefit",
    benefitBody: "Habiba Holdings pays 60% of each session until 31 Dec 2026.",
    companySees: "Habiba Holdings sees",
    companySeesList: ["Your name on their list", "Their budget used, in total, in steps"],
    neverSees: "Never sees",
    neverSeesList: ["Whether you booked, when or with whom", "Anything said or written"],
    tabs: { home: "Home", find: "Find", record: "Record", me: "Me" },
    sos: "SOS",
    sosTitle: "Help now",
    sosBody: "These are phone numbers, not a chat. They answer day and night.",
    line105: "Mental health line, Egypt. Press 1 for Arabic, then 1.",
    line123: "Ambulance, if you are in danger now.",
    back: "Back",
  };

export type Copy = typeof en;

const ar: Copy = {
    evening: "مساء الخير يا مريم",
    arriving: "كيف تشعرين اليوم؟",
    moods: { calm: "هادئة", anxious: "قلقة", low: "مُتعَبة", sleep: "لا أنام" },
    moodNote: {
      calm: "يسعدنا ذلك. تمرين قصير قد يساعدك على البقاء هكذا.",
      anxious: "لا داعي لانتظار الخميس. يمكن لأحد أن يتحدث معك الآن.",
      low: "شكرًا لأنك قلتِ ذلك. يمكن لأحد أن يتحدث معك الآن، أو اكتبي ما تشعرين به أولًا.",
      sleep: "النوم أكثر ما يأتي الناس من أجله. هؤلاء يمكنهم المساعدة.",
    },
    freeNow: "معالجون متاحون الآن",
    talkNow: "تحدثي مع أحد الآن",
    heroTitle: "يمكن لأحد أن يسمعك خلال دقائق",
    search: "ابحثي عن معالج أو موضوع أو لغة",
    topics: "المواضيع",
    topicNames: { anxiety: "القلق", sleep: "النوم", relationships: "العلاقات", grief: "الفقد", stress: "ضغط العمل", family: "الأسرة" },
    availableNow: "متاح الآن",
    seeAll: "عرض الكل",
    nextSession: "جلستك القادمة",
    inDays: "بعد يومين",
    exercises: "دقيقتان لكِ",
    breathe: "تنفّسي مع الدائرة",
    breatheIn: "شهيق",
    breatheOut: "زفير",
    ground: "5 أشياء ترينها",
    yourRecord: "سجلّك",
    recordLine: "ملخّصان من معالجَين. أنتِ من يقرر من يقرأهما.",
    asking: "شخص واحد يطلب قراءته",
    youPay: "تدفعين",
    covers: "حبيبة القابضة تدفع 60%",
    start: "ابدئي",
    results: "معالجين",
    filters: { now: "متاح الآن", arabic: "العربية", english: "الإنجليزية", under30: "أقل من 35$ عليكِ", women: "معالِجات" },
    noResults: "لا أحد يطابق كل ذلك. جرّبي إزالة أحد الخيارات.",
    verified: "موثّق",
    years: "سنوات",
    reliability: "حضرت",
    of: "من",
    sessions: "جلسات",
    about: "نبذة",
    specialities: "تعمل مع",
    times: "أو اختاري موعدًا",
    today: "اليوم",
    tomorrow: "غدًا",
    startNow: "ابدئي الآن",
    bookingTitle: "ابدئي مع",
    length: "المدة",
    min30: "30 دقيقة",
    min60: "60 دقيقة",
    session: "الجلسة",
    vat: "ضريبة 14% على حصتك",
    payWith: "الدفع عبر",
    card: "بطاقة",
    cardNote: "تدخلين الغرفة خلال ثوانٍ",
    transfer: "تحويل بنكي",
    transferNote: "يراجعه شخص، عادةً خلال دقائق",
    startAndPay: "ابدئي وادفعي",
    held: "محجوزة لكِ",
    consentTitle: "هل تُكتب ملاحظات سارة من تسجيل؟",
    consentBody: "نعم، وتُكتب مسودة ملاحظة من الجلسة. تقرؤها سارة وتوقّعها قبل أن يصلك شيء. يمكنك إيقاف التسجيل في أي لحظة.",
    yes: "نعم، يمكنكم التسجيل",
    no: "لا، لا تسجّلوا",
    either: "في الحالتين تستمر الجلسة.",
    goIn: "ادخلي",
    recording: "يُسجَّل",
    notRecording: "لا يُسجَّل",
    stopRecording: "أوقفي التسجيل",
    stopped: "توقف التسجيل. لا يُحفظ شيء من الآن.",
    end: "إنهاء",
    minimise: "تصغير",
    stillWriting: "ما زالت سارة تكتب ملخّصك",
    stillWritingBody: "لا يصلك شيء كتبته آلة قبل أن تقرأه وتوقّعه.",
    signed: "بتوقيع",
    psychologist: "أخصائية نفسية إكلينيكية",
    summary: "تحدثنا عن الاستيقاظ في الرابعة فجرًا وعن روتين التهدئة الذي التزمتِ به أربع ليالٍ. ساعد تمرين التنفس يوم الثلاثاء. الخطوة التالية: استمري في الروتين أسبوعًا آخر.",
    nextStep: "خطوتك التالية",
    nextStepBody: "الهاتف بعيدًا قبل النوم بساعة، أربع ليالٍ هذا الأسبوع.",
    whoReads: "من يمكنه قراءة سجلّك",
    canRead: "يمكنه القراءة",
    askingNow: "يطلب الآن",
    yes24: "نعم، لمدة 24 ساعة",
    yesUntil: "حتى أغيّر رأيي",
    noThanks: "لا",
    granted: "يمكن لد. كريم قراءة ملخّصاتك لمدة 24 ساعة.",
    stop: "إيقاف",
    benefit: "ميزتك",
    benefitBody: "حبيبة القابضة تدفع 60% من كل جلسة حتى 31 ديسمبر 2026.",
    companySees: "ترى حبيبة القابضة",
    companySeesList: ["اسمك في قائمتها", "ما استُخدم من ميزانيتها إجمالًا، على مراحل"],
    neverSees: "لا ترى أبدًا",
    neverSeesList: ["إن كنتِ حجزتِ أو متى أو مع من", "أي شيء قيل أو كُتب"],
    tabs: { home: "الرئيسية", find: "ابحثي", record: "سجلّي", me: "حسابي" },
    sos: "طوارئ",
    sosTitle: "مساعدة الآن",
    sosBody: "هذه أرقام هاتف، لا محادثة. يردّون ليلًا ونهارًا.",
    line105: "خط الصحة النفسية، مصر. اضغطي 1 للعربية ثم 1.",
    line123: "الإسعاف، إن كنتِ في خطر الآن.",
    back: "رجوع",
};

export const COPY: Record<Lang, Copy> = { en, ar };
