import { readFileSync } from "node:fs";
import { browser, go, anatomy, text, shot, PHONE } from "./lib.mjs";
const link = readFileSync(".walkthrough2/invite.txt","utf8").trim();
const people = JSON.parse(readFileSync(".walkthrough2/people.json","utf8"));
const q = people.patient;
const b = await browser();
const ctx = await b.newContext({ viewport: PHONE });
const p = await ctx.newPage();
const step = async (n, chars=1200) => { console.log(`\n### ${n} ${p.url()}`, JSON.stringify(await anatomy(p))); console.log((await text(p)).slice(0,chars)); await shot(p, n); };
await p.goto(link.replace("/patient/invite/", "/patient/signup?invite=").replace(/\/$/,""), { waitUntil: "networkidle" });
await p.fill("input[name=firstName]", q.first);
await p.fill("input[name=lastName]", q.last);
await p.selectOption("select[name=timezone]", "Africa/Cairo").catch((e)=>console.log("tz", e.message.slice(0,60)));
await p.fill("input[name=password]", q.password);
await p.getByRole("button", { name: /^Create account$/i }).click();
await p.waitForTimeout(6000);
await step("p03-after-signup", 1500);
await ctx.storageState({ path: ".walkthrough2/state-patient.json" });
await b.close();
