import { browser, go, anatomy, text, shot, LAPTOP } from "./lib.mjs";
const b = await browser();
const ctx = await b.newContext({ viewport: LAPTOP, storageState: ".walkthrough2/state-therapist.json" });
const p = await ctx.newPage();
const step = async (n) => { console.log(`\n### ${n} ${p.url()}`); console.log(JSON.stringify(await anatomy(p))); await shot(p, n); };
await go(p, "/onboarding");
await p.selectOption("#country", "EG").catch((e)=>console.log("country", e.message.slice(0,80)));
await p.fill("#licenseBody", "Egyptian Ministry of Health");
await p.fill("#licenseNumber", "PSY-44120");
await p.fill("#licenseExpiry", "2028-06-30");
await p.locator("label", { hasText: /^Arabic$/ }).first().click({ timeout: 5000 }).catch((e)=>console.log("skip Arabic", e.message.slice(0,60)));
await p.locator("label", { hasText: /^English$/ }).first().click({ timeout: 5000 }).catch((e)=>console.log("skip English", e.message.slice(0,60)));
await p.locator("label", { hasText: /^Anxiety$/ }).first().click({ timeout: 5000 }).catch((e)=>console.log("skip Anxiety", e.message.slice(0,60)));
await p.locator("label", { hasText: /^Trauma & PTSD$/ }).first().click({ timeout: 5000 }).catch((e)=>console.log("skip Trauma & PTSD", e.message.slice(0,60)));
await p.getByRole("button", { name: "Save details" }).click();
await p.waitForLoadState("networkidle").catch(()=>{});
await step("t04-onboarding-saved");
console.log((await text(p)).split("What is still missing")[1]?.slice(0,600) ?? "(no missing block)");
const submit = p.getByRole("button", { name: "Submit for verification" });
console.log("submit disabled:", await submit.isDisabled().catch(()=>"n/a"));
await submit.click().catch((e)=>console.log("submit click failed", e.message));
await p.waitForLoadState("networkidle").catch(()=>{});
await step("t05-after-submit");
console.log((await text(p)).slice(0, 1500));
await b.close();
