import { execFileSync } from "node:child_process";
import { chromium } from "playwright";
import { anatomy, text, shot, LAPTOP, BASE } from "./lib.mjs";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium", args: ["--no-sandbox","--use-fake-ui-for-media-stream","--use-fake-device-for-media-stream","--autoplay-policy=no-user-gesture-required"] });
const ctx = await b.newContext({ viewport: LAPTOP, storageState: ".walkthrough2/state-therapist.json", permissions: ["microphone"] });
const p = await ctx.newPage();
await p.goto(`${BASE}/sessions/new`, { waitUntil: "networkidle" });
await p.getByRole("button", { name: /In person/i }).first().click();
await p.selectOption("select[name=patientId]", { label: "Layla Mansour" }).catch(e=>console.log("sel", e.message.slice(0,50)));
await p.getByRole("button", { name: /Start session now/i }).click();
await p.waitForURL(/\/sessions\/[0-9a-f-]+\/room/, { timeout: 30000 });
const id = p.url().match(/sessions\/([0-9a-f-]+)\/room/)[1];
console.log("SESSION", id);
await p.getByRole("button", { name: /^Start session$/i }).click();
await p.waitForTimeout(20000);
execFileSync("node", ["--import","tsx","--conditions=react-server",".walkthrough2/seed-risk.ts", id], { stdio: "inherit" });
await p.getByRole("button", { name: /End session/i }).click();
await p.waitForURL(/\/sessions\/[0-9a-f-]+$/, { timeout: 60000 }).catch(()=>{});
await p.waitForTimeout(12000);
await p.reload({ waitUntil: "networkidle" });
console.log("### t23-risk", p.url(), JSON.stringify(await anatomy(p)));
console.log((await text(p)).slice(0,2500).replace(/\n{2,}/g,"\n"));
await shot(p, "t23-session-risk");
await b.close();
