import { browser, go, text, shot, PHONE, LAPTOP } from "./lib.mjs";
const b = await browser();
const pctx = await b.newContext({ viewport: PHONE, storageState: ".walkthrough2/state-patient.json" });
const p = await pctx.newPage();
await go(p, "/patient/consent");
await p.locator("select").first().selectOption({ index: 1 }).catch(e=>console.log("sel", e.message.slice(0,50)));
await p.locator("textarea").first().fill("I am seeing somebody new and I would like them to have my history.");
await p.getByRole("button", { name: /^Ask them$/i }).click();
await p.waitForTimeout(4000);
console.log("=== patient asked ===\n" + (await text(p)).slice(0,500).replace(/\n{2,}/g,"\n"));
await shot(p, "p26-ask-history");
const tctx = await b.newContext({ viewport: LAPTOP, storageState: ".walkthrough2/state-therapist.json" });
const t = await tctx.newPage();
await go(t, "/connect");
console.log("\n=== therapist connect ===\n" + (await text(t)).split("Settings")[1]?.slice(0,900).replace(/\n{2,}/g,"\n"));
console.log("BUTTONS:", await t.evaluate(()=>[...document.querySelectorAll("button")].map(b=>b.innerText.trim()).filter(Boolean).join(" | ")));
await shot(t, "t28-ask-request");
await b.close();
