import { readFileSync } from "node:fs";
import { browser, go, anatomy, text, shot, LAPTOP } from "./lib.mjs";
const people = JSON.parse(readFileSync(".walkthrough2/people.json", "utf8"));
const b = await browser();
const ctx = await b.newContext({ viewport: LAPTOP });
const p = await ctx.newPage();
const step = async (n, chars=900) => { console.log(`\n### ${n} ${p.url()}`, JSON.stringify(await anatomy(p))); console.log((await text(p)).slice(0,chars)); await shot(p, n); };
await go(p, "/staff/sign-in");
await step("a01-staff-signin");
await p.getByLabel(/email/i).first().fill(people.admin.email);
await p.getByLabel(/password/i).first().fill(people.admin.password);
await p.getByRole("button", { name: /sign in/i }).first().click();
await p.waitForURL((u)=>!u.pathname.includes("sign-in"), { timeout: 20000 }).catch(()=>{});
await p.waitForLoadState("networkidle").catch(()=>{});
await step("a02-admin-home", 1600);
await ctx.storageState({ path: ".walkthrough2/state-admin.json" });
await go(p, "/admin/verifications");
await step("a03-verifications", 1600);
await b.close();
