import { readFileSync } from "node:fs";
import { browser, go, anatomy, text, shot, LAPTOP } from "./lib.mjs";
const people = JSON.parse(readFileSync(".walkthrough2/people.json", "utf8"));
const q = people.patient;
const b = await browser();
const ctx = await b.newContext({ viewport: LAPTOP, storageState: ".walkthrough2/state-therapist.json" });
const p = await ctx.newPage();
const step = async (n, chars=1200) => { console.log(`\n### ${n} ${p.url()}`, JSON.stringify(await anatomy(p))); console.log((await text(p)).slice(0,chars)); await shot(p, n); };
await go(p, "/patients");
await p.getByRole("button", { name: /add a patient/i }).first().click();
await p.waitForTimeout(1000);
await p.fill("input[name=firstName]", q.first);
await p.fill("input[name=lastName]", q.last);
await p.selectOption("select[name=phoneCountry]", "EG").catch(async()=>{ await p.selectOption("select[name=phoneCountry]", { label: /Egypt/ }); });
await p.fill("input[name=phone]", "1001234567");
await p.fill("input[name=email]", q.email);
await p.getByRole("button", { name: /^Add patient$/i }).click();
await p.waitForTimeout(4000);
await step("t13-patient-added");
await b.close();
