import { browser, go, LAPTOP } from "./lib.mjs";
const b = await browser();
const ctx = await b.newContext({ viewport: LAPTOP, storageState: ".walkthrough2/state-therapist.json" });
const p = await ctx.newPage();
await go(p, "/onboarding");
const chip = p.locator("label", { hasText: /^Arabic$/ }).first();
console.log("chip count", await p.locator("label", { hasText: /^Arabic$/ }).count());
await chip.click();
console.log("checked after click:", await p.locator("input[name=languages][value=Arabic]").isChecked());
await p.locator("label", { hasText: /^Anxiety$/ }).first().click();
console.log("anxiety checked:", await p.locator("input[name=specialties][value=Anxiety]").isChecked());
await p.getByRole("button", { name: "Save details" }).click();
await p.waitForTimeout(3000);
console.log("checked after save:", await p.locator("input[name=languages][value=Arabic]").isChecked());
await go(p, "/onboarding");
console.log("checked after reload:", await p.locator("input[name=languages][value=Arabic]").isChecked());
console.log("anxiety after reload:", await p.locator("input[name=specialties][value=Anxiety]").isChecked());
const body = await p.locator("body").innerText();
console.log("missing:", body.split("catch up.")[1]?.split("Submit")[0]?.trim());
await b.close();
