import type { MetadataRoute } from "next";

import { publishedSlugs } from "@/lib/content/service";
import { env } from "@/lib/env";
import { LOCALES } from "@/lib/i18n/config";
import { alternatesFor, localisedPath } from "@/lib/i18n/paths";

/**
 * Only public marketing pages and the radar. Nothing behind a login, and
 * emphatically nothing under `/join/*`.
 *
 * Built from what is actually published in the CMS, so unpublishing a page
 * removes it from the sitemap rather than leaving a 404 advertised to crawlers.
 *
 * ## 🔴 31.1 — every page, in both languages
 *
 * Each URL is listed once per language and carries the same `alternates` block
 * the page itself declares, generated by the **same function**. A sitemap that
 * computed its own Arabic URLs would be a second implementation of the rule,
 * and the day the two disagreed the sitemap would be advertising addresses the
 * pages do not claim.
 */
export const revalidate = 3600;

type Entry = { path: string; changeFrequency: "hourly" | "weekly" | "monthly"; priority: number; lastModified?: Date };

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const pages = await publishedSlugs();

  const entries: Entry[] = [
    { path: "/", changeFrequency: "weekly", priority: 1 },
    // The one page whose value is that it is up to the minute.
    { path: "/radar", changeFrequency: "hourly", priority: 0.9 },
    ...pages
      .filter((page) => page.slug !== "home")
      .map((page) => ({
        path: `/${page.slug}`,
        lastModified: page.updatedAt,
        changeFrequency: "monthly" as const,
        priority: 0.7,
      })),
  ];

  return entries.flatMap((entry) =>
    LOCALES.map((locale) => ({
      url: `${env.appUrl}${localisedPath(entry.path, locale)}`,
      lastModified: entry.lastModified,
      changeFrequency: entry.changeFrequency,
      priority: entry.priority,
      alternates: { languages: alternatesFor(entry.path, env.appUrl).languages },
    })),
  );
}
