import countryTable from "@/lib/countries.json";

/**
 * Just enough geography to draw a radar.
 *
 * No geo-IP, no map tiles, no external service. Two reasons: a clinician's
 * precise location is not ours to publish — country granularity is the most a
 * patient needs and the least we can leak — and a public marketing page must
 * not make a third-party request on every visit.
 *
 * The land mask below is a deliberately coarse equirectangular silhouette. It
 * is a backdrop, not a map: nobody should navigate by it.
 */

export const LAT_TOP = 78;
export const LAT_BOTTOM = -58;
export const GRID_COLS = 60;
export const GRID_ROWS = 28;

/**
 * Land, as longitude spans per latitude band, north to south. Written as
 * degrees rather than grid indices so it can be read and corrected by eye.
 */
const LAND_BANDS: { lat: number; spans: [number, number][] }[] = [
  { lat: 78, spans: [[-125, -80], [-73, -20], [10, 25], [55, 140]] },
  { lat: 73, spans: [[-128, -65], [-55, -20], [20, 180]] },
  { lat: 68, spans: [[-165, -140], [-138, -65], [-52, -20], [8, 180]] },
  { lat: 63, spans: [[-166, -134], [-132, -60], [-45, -20], [-24, -13], [4, 180]] },
  { lat: 58, spans: [[-162, -134], [-130, -58], [-8, -1], [3, 180]] },
  { lat: 53, spans: [[-135, -55], [-11, 30], [30, 180]] },
  { lat: 48, spans: [[-128, -58], [-6, 40], [40, 150]] },
  { lat: 43, spans: [[-125, -62], [-9, 45], [45, 148]] },
  { lat: 38, spans: [[-123, -72], [-10, 45], [45, 142]] },
  { lat: 33, spans: [[-121, -76], [-17, -1], [4, 38], [38, 136]] },
  { lat: 28, spans: [[-116, -78], [-17, 36], [36, 122]] },
  { lat: 23, spans: [[-111, -84], [-17, 36], [36, 95], [95, 112]] },
  { lat: 18, spans: [[-106, -84], [-17, 42], [42, 95], [95, 108]] },
  { lat: 13, spans: [[-93, -82], [-17, 46], [72, 95], [95, 110]] },
  { lat: 8, spans: [[-85, -76], [-73, -59], [-13, 48], [74, 82], [95, 118]] },
  { lat: 3, spans: [[-80, -49], [-9, 44], [95, 122]] },
  { lat: -2, spans: [[-79, -44], [8, 42], [98, 140]] },
  { lat: -7, spans: [[-78, -36], [11, 41], [104, 150]] },
  { lat: -12, spans: [[-76, -35], [12, 41], [122, 151]] },
  { lat: -17, spans: [[-72, -38], [12, 41], [113, 147]] },
  { lat: -22, spans: [[-70, -41], [13, 36], [113, 152]] },
  { lat: -27, spans: [[-72, -47], [15, 33], [113, 153]] },
  { lat: -32, spans: [[-73, -52], [17, 32], [115, 152]] },
  { lat: -37, spans: [[-74, -56], [18, 27], [138, 150], [166, 179]] },
  { lat: -42, spans: [[-75, -62], [144, 149], [168, 177]] },
  { lat: -47, spans: [[-75, -65]] },
  { lat: -52, spans: [[-75, -67]] },
  { lat: -57, spans: [] },
];

export type LandDot = { x: number; y: number };

/** The land mask as normalised 0–1 coordinates, ready to place in an SVG. */
export function landDots(): LandDot[] {
  const dots: LandDot[] = [];
  LAND_BANDS.forEach((band, row) => {
    const y = row / (GRID_ROWS - 1);
    for (let col = 0; col < GRID_COLS; col += 1) {
      const lon = -180 + (col * 360) / GRID_COLS;
      if (band.spans.some(([from, to]) => lon >= from && lon <= to)) {
        dots.push({ x: col / (GRID_COLS - 1), y });
      }
    }
  });
  return dots;
}

/** Equirectangular projection into the same 0–1 space as the land mask. */
export function project(lon: number, lat: number): { x: number; y: number } {
  const x = (lon + 180) / 360;
  const y = (LAT_TOP - lat) / (LAT_TOP - LAT_BOTTOM);
  return { x: clamp01(x), y: clamp01(y) };
}

function clamp01(value: number): number {
  return Math.min(1, Math.max(0, value));
}

/**
 * Every country the globe can draw, with the centre of its main landmass.
 *
 * Generated by `scripts/build-world.mjs` from the same Natural Earth data the
 * globe renders, so a country can never be offered in a dropdown that the map
 * has no outline for. It replaced a hand-typed table of ninety centroids that
 * was, inevitably, missing most of the world.
 *
 * Four kilobytes. The outlines themselves are a separate 115 kB file that only
 * the globe imports — reading a country's *name* must not pull the whole world
 * into a bundle.
 */
const COUNTRIES: Record<string, { name: string; lon: number; lat: number }> = Object.fromEntries(
  Object.entries(countryTable as unknown as Record<string, [string, number, number]>).map(
    ([code, [name, lon, lat]]) => [code, { name, lon, lat }],
  ),
);

/**
 * The flag emoji for an ISO-3166 alpha-2 code.
 *
 * Computed from regional indicator symbols rather than shipped as a lookup
 * table or a sprite sheet: no asset, no licence, correct for every code, and it
 * renders in the user's own font. Windows shows letters instead of a flag,
 * which is why nothing here depends on the flag alone to convey meaning — the
 * country name is always beside it.
 */
export function countryFlag(code: string | null | undefined): string {
  if (!code || code.length !== 2) return "🏳️";
  const upper = code.toUpperCase();
  if (!/^[A-Z]{2}$/.test(upper)) return "🏳️";
  return String.fromCodePoint(
    ...[...upper].map((letter) => 0x1f1e6 + letter.charCodeAt(0) - 65),
  );
}

export const COUNTRY_OPTIONS = Object.entries(COUNTRIES)
  .map(([code, value]) => ({ code, name: value.name, flag: countryFlag(code) }))
  .sort((a, b) => a.name.localeCompare(b.name));

export function countryName(code: string | null | undefined): string | null {
  return code ? (COUNTRIES[code]?.name ?? null) : null;
}

export function countryPoint(code: string | null | undefined): { x: number; y: number } {
  const country = code ? COUNTRIES[code] : undefined;
  if (!country) return project(-30, 20);
  return project(country.lon, country.lat);
}

/** Languages offered on the radar. An allowlist, not a free-text field. */
export const RADAR_LANGUAGES = [
  "English",
  "Spanish",
  "French",
  "German",
  "Portuguese",
  "Italian",
  "Dutch",
  "Arabic",
  "Hebrew",
  "Turkish",
  "Russian",
  "Ukrainian",
  "Polish",
  "Hindi",
  "Urdu",
  "Bengali",
  "Mandarin",
  "Cantonese",
  "Japanese",
  "Korean",
  "Tagalog",
  "Vietnamese",
  "Thai",
  "Indonesian",
  "Swahili",
] as const;

/**
 * A flag for each language, purely as a visual anchor in the picker.
 *
 * Fraught by nature — a language is not a country, and Arabic, Spanish and
 * English each belong to dozens of places. The flag is decoration next to the
 * name, never a substitute for it, and where no single flag is defensible the
 * entry is a neutral globe rather than an implied claim about who owns the
 * language.
 */
export const LANGUAGE_FLAGS: Record<string, string> = {
  English: "🌐",
  Spanish: "🌐",
  French: "🇫🇷",
  German: "🇩🇪",
  Portuguese: "🇵🇹",
  Italian: "🇮🇹",
  Dutch: "🇳🇱",
  Arabic: "🌐",
  Hebrew: "🇮🇱",
  Turkish: "🇹🇷",
  Russian: "🇷🇺",
  Ukrainian: "🇺🇦",
  Polish: "🇵🇱",
  Hindi: "🇮🇳",
  Urdu: "🇵🇰",
  Bengali: "🇧🇩",
  Mandarin: "🇨🇳",
  Cantonese: "🇭🇰",
  Japanese: "🇯🇵",
  Korean: "🇰🇷",
  Tagalog: "🇵🇭",
  Vietnamese: "🇻🇳",
  Thai: "🇹🇭",
  Indonesian: "🇮🇩",
  Swahili: "🌐",
};

export function languageFlag(language: string): string {
  return LANGUAGE_FLAGS[language] ?? "🌐";
}

/** What a clinician says they work with. Also an allowlist. */
export const RADAR_SPECIALTIES = [
  "Anxiety",
  "Depression",
  "Trauma & PTSD",
  "Grief & loss",
  "Panic attacks",
  "Suicidal thoughts",
  "Self-harm",
  "Addiction",
  "Eating disorders",
  "OCD",
  "Bipolar",
  "Relationships",
  "Family conflict",
  "Work stress & burnout",
  "Identity & LGBTQ+",
  "Postnatal",
  "Sleep",
  "Chronic illness",
] as const;
