import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, CheckCircle, AlertCircle, ArrowRight, ExternalLink } from "lucide-react";

interface IntegrationDoc {
  name: string;
  category: string;
  status: "live" | "beta" | "planned";
  logo: string;
  tagline: string;
  overview: string;
  useCases: string[];
  setupSteps: string[];
  dataFlows: Array<{ direction: string; fields: string[] }>;
  prerequisites: string[];
  notes?: string;
  docsUrl?: string;
}

const INTEGRATION_DOCS: Record<string, IntegrationDoc> = {
  simplepractice: {
    name: "SimplePractice",
    category: "EHR / Practice Management",
    status: "planned",
    logo: "SP",
    tagline: "Import your entire SimplePractice practice into 24Therapy.ai",
    overview:
      "The SimplePractice integration allows solo therapists and group practices to migrate their patient records, session history, and clinical notes from SimplePractice into 24Therapy.ai — and keep them in sync going forward. Once connected, 24Therapy.ai enriches your existing records with AI-generated insights, without any manual re-entry.",
    useCases: [
      "One-time migration from SimplePractice to 24Therapy.ai",
      "Ongoing bidirectional sync for hybrid practices",
      "Import patient intake forms and treatment history",
      "Sync calendar and booking availability",
    ],
    setupSteps: [
      "Contact support to join the SimplePractice integration beta",
      "Generate a SimplePractice API token from your account settings",
      "Enter the token in 24Therapy Settings → Integrations → SimplePractice",
      "Choose sync scope: patient records, notes, calendar, or all",
      "Run a test import on a single patient before bulk migration",
      "Monitor import logs and review AI-enriched records",
    ],
    dataFlows: [
      {
        direction: "SimplePractice → 24Therapy.ai",
        fields: ["Patient demographics", "Diagnosis codes (ICD-10)", "Session notes", "Treatment plans", "Appointment history"],
      },
      {
        direction: "24Therapy.ai → SimplePractice",
        fields: ["AI-generated SOAP notes", "Session summaries", "Assessment scores", "Updated availability"],
      },
    ],
    prerequisites: [
      "SimplePractice Professional or Group plan (API access required)",
      "24Therapy.ai Group plan or higher",
    ],
    notes: "This integration is currently in private beta. Contact support@24therapy.ai to join the waitlist.",
  },
  therapynotes: {
    name: "TherapyNotes",
    category: "EHR / EMR",
    status: "planned",
    logo: "TN",
    tagline: "Migrate TherapyNotes records to 24Therapy.ai with AI enrichment",
    overview:
      "The TherapyNotes integration enables practices to migrate patient data, historical session notes, and billing records from TherapyNotes into 24Therapy.ai. All migrated notes are processed by the 24Therapy.ai AI to generate structured patient memory nodes automatically.",
    useCases: [
      "Full practice migration from TherapyNotes",
      "Import historical session notes for AI memory graph construction",
      "Transfer billing history and insurance information",
      "Continue accepting new patients in 24Therapy.ai while completing the migration",
    ],
    setupSteps: [
      "Export your TherapyNotes data via Settings → Data Export (XML or CSV)",
      "Upload the export file in 24Therapy Settings → Integrations → Import → TherapyNotes",
      "Map TherapyNotes fields to 24Therapy.ai schema (guided wizard)",
      "Preview 5 patient records before full import",
      "Run full import — AI memory graph builds automatically in background",
      "Verify imported records and deactivate TherapyNotes when ready",
    ],
    dataFlows: [
      {
        direction: "TherapyNotes → 24Therapy.ai",
        fields: ["Patient demographics", "Session notes (all formats)", "Diagnoses and treatment plans", "Insurance information", "Billing records"],
      },
    ],
    prerequisites: [
      "TherapyNotes account with data export access",
      "24Therapy.ai Therapist plan or higher",
    ],
    notes: "Migration import is free and included with all plans. Ongoing sync is available on Group plans and above.",
  },
  epic: {
    name: "Epic",
    category: "Enterprise EHR",
    status: "planned",
    logo: "E",
    tagline: "FHIR R4 bidirectional sync with Epic's MyChart and Cogito ecosystem",
    overview:
      "The Epic integration uses the HL7 FHIR R4 standard to create a bidirectional data bridge between your Epic environment and 24Therapy.ai. Clinical notes generated by the AI Scribe can be pushed directly into the Epic chart, and patient demographics, diagnoses, and medications sync automatically before each session.",
    useCases: [
      "Health system-wide mental health AI deployment on Epic infrastructure",
      "AI Scribe notes auto-posted to Epic chart after therapist approval",
      "Patient demographics and medication lists pre-loaded before each session",
      "Outcome measure scores (PHQ-9, GAD-7) pushed as Epic flowsheet rows",
    ],
    setupSteps: [
      "Submit an Epic on FHIR app request via the Epic App Orchard",
      "Provide 24Therapy.ai with your Epic FHIR endpoint and client credentials",
      "Configure scope: which FHIR resources to sync (Patient, Condition, MedicationRequest, etc.)",
      "Run sandbox connectivity test using Epic's open.epic.com test environment",
      "Complete Epic's security review (required for production deployment)",
      "Enable in 24Therapy Settings → Integrations → Epic",
    ],
    dataFlows: [
      {
        direction: "Epic → 24Therapy.ai",
        fields: ["Patient (R4 resource)", "Condition (diagnoses)", "MedicationRequest", "AllergyIntolerance", "Appointment"],
      },
      {
        direction: "24Therapy.ai → Epic",
        fields: ["DocumentReference (session notes)", "Observation (PHQ-9, GAD-7 scores)", "Procedure (session record)"],
      },
    ],
    prerequisites: [
      "Epic version 2020 or later with FHIR R4 support",
      "Epic App Orchard account and security review",
      "24Therapy.ai Enterprise plan",
    ],
    notes: "Epic integration requires 24Therapy.ai Enterprise plan and an Epic implementation specialist engagement. Contact sales@24therapy.ai.",
    docsUrl: "https://open.epic.com",
  },
  cerner: {
    name: "Cerner / Oracle Health",
    category: "Enterprise EHR",
    status: "planned",
    logo: "C",
    tagline: "HL7 FHIR R4 integration with Cerner Millennium and Oracle Health",
    overview:
      "The Cerner integration connects 24Therapy.ai with Cerner Millennium using the HL7 FHIR R4 standard. Mental health session notes generated by the AI Scribe are written back to the Cerner chart as structured DocumentReference resources. Patient context syncs automatically before each session.",
    useCases: [
      "Hospital and health system mental health department deployment",
      "AI Scribe notes written to Cerner chart post-session",
      "Patient demographics, allergies, and medications pre-loaded before sessions",
      "Risk alerts created as ClinicalImpression resources in Cerner",
    ],
    setupSteps: [
      "Register 24Therapy.ai as a CDS Hooks service in your Cerner sandbox",
      "Configure SMART on FHIR launch parameters",
      "Map 24Therapy.ai note formats to Cerner DocumentReference categories",
      "Complete Cerner Code Program security review",
      "Deploy to production via Cerner App Gallery",
      "Enable in 24Therapy Settings → Integrations → Cerner",
    ],
    dataFlows: [
      {
        direction: "Cerner → 24Therapy.ai",
        fields: ["Patient demographics", "Problem list (Conditions)", "Medications", "Allergies", "Encounter history"],
      },
      {
        direction: "24Therapy.ai → Cerner",
        fields: ["Session notes (DocumentReference)", "Outcome measures (Observation)", "Risk assessments (ClinicalImpression)"],
      },
    ],
    prerequisites: [
      "Cerner Millennium with SMART on FHIR support",
      "Cerner Code Program registration",
      "24Therapy.ai Enterprise plan",
    ],
    notes: "Cerner integration is available for Enterprise customers. Contact sales@24therapy.ai for the implementation timeline.",
  },
  athena: {
    name: "Athenahealth",
    category: "EHR / Practice Management",
    status: "planned",
    logo: "A",
    tagline: "FHIR-based patient sync and note push with athenahealth",
    overview:
      "The athenahealth integration connects 24Therapy.ai with the athenaOne EHR platform using HL7 FHIR R4. Patient demographics, diagnoses, and appointment history sync automatically, while AI-generated notes are pushed back as structured athenahealth chart entries.",
    useCases: [
      "Multi-specialty practices using athenahealth for billing and scheduling",
      "Therapists embedded in primary care or pediatric settings",
      "Outcome measure scores posted as athenahealth document notes",
    ],
    setupSteps: [
      "Register as an athenahealth API developer at developer.athenahealth.com",
      "Configure OAuth 2.0 credentials in 24Therapy Settings → Integrations",
      "Select FHIR resource scope for your practice",
      "Test with athenahealth sandbox credentials",
      "Submit for athenahealth marketplace review (required for production)",
    ],
    dataFlows: [
      {
        direction: "athenahealth → 24Therapy.ai",
        fields: ["Patient (FHIR)", "Appointment", "Condition (ICD-10)", "Medication"],
      },
      {
        direction: "24Therapy.ai → athenahealth",
        fields: ["Session notes (DocumentReference)", "PHQ-9 / GAD-7 scores (Observation)"],
      },
    ],
    prerequisites: [
      "athenahealth API access (available on Marketplace tier and above)",
      "24Therapy.ai Group plan or higher",
    ],
  },
  allscripts: {
    name: "Allscripts",
    category: "EHR",
    status: "planned",
    logo: "AL",
    tagline: "Connect Allscripts Sunrise and TouchWorks to 24Therapy.ai",
    overview:
      "The Allscripts integration supports both Sunrise (acute) and TouchWorks (ambulatory) deployments. Clinical notes from 24Therapy.ai sessions are posted to the Allscripts chart using the HL7 CCDA and FHIR interfaces.",
    useCases: [
      "Integrated delivery networks with Allscripts infrastructure",
      "Post-session note push to Allscripts from 24Therapy.ai sessions",
    ],
    setupSteps: [
      "Obtain Allscripts Developer Program access",
      "Configure API credentials in 24Therapy Settings → Integrations",
      "Map note formats to Allscripts document types",
    ],
    dataFlows: [
      {
        direction: "Allscripts → 24Therapy.ai",
        fields: ["Patient demographics", "Problem list", "Medications"],
      },
      {
        direction: "24Therapy.ai → Allscripts",
        fields: ["Session notes (CCDA/FHIR DocumentReference)", "Outcome scores"],
      },
    ],
    prerequisites: [
      "Allscripts Sunrise or TouchWorks with API access",
      "24Therapy.ai Enterprise plan",
    ],
  },
  daily: {
    name: "Daily.co",
    category: "Telehealth Video",
    status: "live",
    logo: "DC",
    tagline: "HIPAA-compliant video sessions — the native 24Therapy.ai infrastructure",
    overview:
      "Daily.co is the embedded video infrastructure powering 24Therapy.ai's telehealth sessions. No setup required — every session room is automatically a HIPAA-compliant Daily.co room with end-to-end encryption, AI scribe integration, and real-time copilot overlay.",
    useCases: [
      "All 24Therapy.ai video sessions (built-in, no configuration needed)",
      "Branded waiting rooms with patient status display",
      "AI Scribe audio capture and real-time transcription",
      "Session recording with HIPAA-compliant encrypted storage",
    ],
    setupSteps: [
      "No setup required — Daily.co is the default video provider for all 24Therapy.ai sessions",
      "Configure recording preferences in Settings → Session Room",
      "Set custom waiting room branding in Settings → Practice Branding",
    ],
    dataFlows: [
      {
        direction: "Daily.co → 24Therapy.ai",
        fields: ["Real-time audio stream (for AI transcription)", "Participant connection events", "Recording completion webhooks"],
      },
    ],
    prerequisites: ["Any 24Therapy.ai plan — included at no extra cost"],
  },
  stripe: {
    name: "Stripe",
    category: "Billing & Payments",
    status: "live",
    logo: "S",
    tagline: "Patient payment collection, subscriptions, and revenue reconciliation",
    overview:
      "Stripe is the payment processing backbone of 24Therapy.ai. All patient payments, subscription billing, and revenue reporting flow through 24Therapy.ai's Stripe integration. No separate Stripe account needed — payments are managed through the therapist dashboard.",
    useCases: [
      "Collect copays and self-pay fees after sessions",
      "Accept HSA/FSA cards for therapy sessions",
      "Manage recurring subscription plans for patients",
      "View real-time revenue in the Analytics dashboard",
    ],
    setupSteps: [
      "No setup required for therapists — Stripe is fully managed by 24Therapy.ai",
      "Set your session rate in Settings → Practice → Billing",
      "Configure payment collection timing (pre-session, post-session, or invoice)",
      "Connect your bank account in Settings → Payouts for fund transfers",
    ],
    dataFlows: [
      {
        direction: "24Therapy.ai → Stripe",
        fields: ["Payment intents", "Subscription charges", "Refund requests"],
      },
      {
        direction: "Stripe → 24Therapy.ai",
        fields: ["Payment confirmations", "Payout notifications", "Dispute webhooks"],
      },
    ],
    prerequisites: ["Any 24Therapy.ai plan — included at no extra cost"],
    notes: "24Therapy.ai processes payments via Stripe Connect. Platform fee is deducted automatically. Payouts are weekly.",
  },
};

const STATUS_STYLES = {
  live: "bg-green-100 text-green-700",
  beta: "bg-amber-100 text-amber-700",
  planned: "bg-slate-100 text-slate-600",
};

const STATUS_LABELS = {
  live: "Live",
  beta: "Beta",
  planned: "On Roadmap",
};

export default async function IntegrationDocPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const doc = INTEGRATION_DOCS[id];

  if (!doc) notFound();

  return (
    <div className="min-h-screen bg-white">
      {/* Breadcrumb */}
      <div className="bg-slate-50 border-b border-slate-200">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center gap-2 text-sm text-slate-500">
          <Link href="/docs" className="hover:text-[#1F5EFF] transition-colors">
            Docs
          </Link>
          <span>/</span>
          <Link href="/features/integrations" className="hover:text-[#1F5EFF] transition-colors">
            Integrations
          </Link>
          <span>/</span>
          <span className="text-slate-900 font-medium">{doc.name}</span>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-6 py-12">
        {/* Back link */}
        <Link
          href="/features/integrations"
          className="inline-flex items-center gap-2 text-sm text-slate-500 hover:text-[#1F5EFF] transition-colors mb-8"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Integrations
        </Link>

        {/* Header */}
        <div className="flex items-start gap-5 mb-8">
          <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-slate-100 to-slate-200 flex items-center justify-center text-slate-700 font-bold text-base flex-shrink-0">
            {doc.logo}
          </div>
          <div>
            <div className="flex items-center gap-3 mb-1">
              <h1 className="text-3xl font-bold text-slate-900">{doc.name}</h1>
              <span className={`text-xs font-semibold px-2.5 py-1 rounded-full ${STATUS_STYLES[doc.status]}`}>
                {STATUS_LABELS[doc.status]}
              </span>
            </div>
            <p className="text-slate-500 text-sm">{doc.category}</p>
            <p className="text-lg text-slate-700 mt-2">{doc.tagline}</p>
          </div>
        </div>

        {/* Status notice */}
        {doc.status !== "live" && (
          <div className="flex items-start gap-3 bg-amber-50 border border-amber-200 rounded-xl p-4 mb-8">
            <AlertCircle className="w-5 h-5 text-amber-600 flex-shrink-0 mt-0.5" />
            <div>
              <p className="font-semibold text-amber-900 text-sm">
                {doc.status === "beta" ? "Beta Integration" : "Coming Soon"}
              </p>
              <p className="text-amber-800 text-sm mt-0.5">
                {doc.notes ||
                  "This integration is on the roadmap. Contact support@24therapy.ai to join the early access waitlist."}
              </p>
            </div>
          </div>
        )}

        {/* Overview */}
        <section className="mb-10">
          <h2 className="text-xl font-bold text-slate-900 mb-3">Overview</h2>
          <p className="text-slate-600 leading-relaxed">{doc.overview}</p>
        </section>

        {/* Use Cases */}
        <section className="mb-10">
          <h2 className="text-xl font-bold text-slate-900 mb-3">Use Cases</h2>
          <ul className="space-y-2">
            {doc.useCases.map((uc) => (
              <li key={uc} className="flex items-start gap-2.5 text-slate-600">
                <CheckCircle className="w-5 h-5 text-[#2EC4B6] flex-shrink-0 mt-0.5" />
                {uc}
              </li>
            ))}
          </ul>
        </section>

        {/* Prerequisites */}
        <section className="mb-10">
          <h2 className="text-xl font-bold text-slate-900 mb-3">Prerequisites</h2>
          <ul className="space-y-2">
            {doc.prerequisites.map((req) => (
              <li key={req} className="flex items-start gap-2.5 text-slate-600">
                <div className="w-1.5 h-1.5 rounded-full bg-slate-400 flex-shrink-0 mt-2" />
                {req}
              </li>
            ))}
          </ul>
        </section>

        {/* Data Flows */}
        <section className="mb-10">
          <h2 className="text-xl font-bold text-slate-900 mb-3">Data Flows</h2>
          <div className="space-y-4">
            {doc.dataFlows.map((flow) => (
              <div key={flow.direction} className="bg-slate-50 rounded-xl border border-slate-200 p-5">
                <p className="text-sm font-semibold text-[#0A2342] mb-2">{flow.direction}</p>
                <div className="flex flex-wrap gap-2">
                  {flow.fields.map((field) => (
                    <span key={field} className="text-xs bg-white border border-slate-200 text-slate-600 px-2.5 py-1 rounded-lg">
                      {field}
                    </span>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Setup Steps */}
        <section className="mb-10">
          <h2 className="text-xl font-bold text-slate-900 mb-3">Setup Steps</h2>
          <ol className="space-y-3">
            {doc.setupSteps.map((step, i) => (
              <li key={i} className="flex items-start gap-3">
                <span className="w-6 h-6 rounded-full bg-[#0A2342] text-white text-xs font-bold flex items-center justify-center flex-shrink-0 mt-0.5">
                  {i + 1}
                </span>
                <p className="text-slate-600 text-sm leading-relaxed">{step}</p>
              </li>
            ))}
          </ol>
        </section>

        {/* External docs */}
        {doc.docsUrl && (
          <div className="mb-10">
            <a
              href={doc.docsUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 text-sm text-[#1F5EFF] font-medium hover:underline"
            >
              Official {doc.name} developer documentation
              <ExternalLink className="w-3.5 h-3.5" />
            </a>
          </div>
        )}

        {/* CTA */}
        <div className="bg-gradient-to-br from-[#0A2342] to-[#1a3a6a] rounded-2xl p-8 text-white text-center">
          <h3 className="text-xl font-bold mb-2">
            {doc.status === "live" ? "Already Included in Your Plan" : "Join the Integration Waitlist"}
          </h3>
          <p className="text-white/70 text-sm mb-6">
            {doc.status === "live"
              ? "This integration is available with all 24Therapy.ai plans at no extra cost."
              : `Be notified when the ${doc.name} integration launches.`}
          </p>
          <div className="flex flex-wrap justify-center gap-3">
            {doc.status === "live" ? (
              <Link
                href="/signup"
                className="bg-[#2EC4B6] text-white px-6 py-2.5 rounded-xl font-semibold hover:bg-[#26b0a2] transition inline-flex items-center gap-2 text-sm"
              >
                Get Started Free <ArrowRight className="w-4 h-4" />
              </Link>
            ) : (
              <Link
                href="/contact?type=integration"
                className="bg-[#2EC4B6] text-white px-6 py-2.5 rounded-xl font-semibold hover:bg-[#26b0a2] transition inline-flex items-center gap-2 text-sm"
              >
                Join Waitlist <ArrowRight className="w-4 h-4" />
              </Link>
            )}
            <Link
              href="/features/integrations"
              className="border border-white/30 text-white px-6 py-2.5 rounded-xl font-semibold hover:bg-white/10 transition text-sm"
            >
              All Integrations
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
