import { BASE, browser, page, shot, text } from "./lib.mjs";
import { signIn, clickButton } from "./lib2.mjs";
const b = await browser();
const p = await page(b, "t");
await signIn(p, BASE, "yasmin@clinic.test", "walkthrough-therapist-1");
await shot(p, "08-onboarding-complete");
await clickButton(p, "Submit for verification");
console.log("url:", p.url());
const t = await text(p);
console.log(t.slice(0, 800));
await shot(p, "09-submitted");
await b.close();
