import { BASE, browser, page, shot, text } from "./lib.mjs";
import { signIn, clickButton } from "./lib2.mjs";
const b = await browser();
const p = await page(b, "admin");
console.log("admin lands on:", await signIn(p, BASE, "admin@24therapy.ai", "Purge22-Walkthrough-Admin", "/staff/sign-in"));
await shot(p, "10-admin-home");
const t = await text(p);
console.log(t.slice(0, 900));
console.log("--- links ---");
console.log((await p.locator("a[href]").evaluateAll(els => [...new Set(els.map(e => e.getAttribute("href")))])).filter(h => h?.startsWith("/admin")).join(" "));
await b.close();
