import { BASE, browser, page, shot, text } from "./lib.mjs";
import { signIn, clickButton } from "./lib2.mjs";
const b = await browser();
const p = await page(b, "t");
console.log("therapist lands on:", await signIn(p, BASE, "yasmin@clinic.test", "walkthrough-therapist-1"));
await shot(p, "13-therapist-dashboard");
const t = await text(p);
console.log(t.slice(0, 700));
console.log("--- nav links ---", (await p.locator("a[href]").evaluateAll(e => [...new Set(e.map(x => x.getAttribute("href")))])).filter(Boolean).slice(0, 20).join(" "));
await b.close();
