import { BASE, browser, page, shot, text } from "./lib.mjs";
import { signIn, clickButton } from "./lib2.mjs";
const b = await browser();
const p = await page(b, "t");
await signIn(p, BASE, "yasmin@clinic.test", "walkthrough-therapist-1");
await p.goto(`${BASE}/patients`, { waitUntil: "networkidle" });
await shot(p, "14-patients-empty");
console.log("PATIENTS:\n" + (await text(p)).slice(0, 500));
console.log("buttons:", (await p.locator("button, a[href]").allTextContents()).map(s=>s.trim()).filter(Boolean).slice(0,15));
await b.close();
