import { BASE, browser, page, shot, text } from "./lib.mjs";
import { signIn, clickButton } from "./lib2.mjs";
const b = await browser();
const p = await page(b, "t");
await signIn(p, BASE, "yasmin@clinic.test", "walkthrough-therapist-1");
await p.goto(`${BASE}/patients`, { waitUntil: "networkidle" });
await clickButton(p, "Add a patient");
await p.waitForTimeout(800);
console.log("url:", p.url());
console.log("fields:", await p.locator("input,select,textarea").evaluateAll(e => e.map(x => `${x.tagName.toLowerCase()}:${x.name || x.id}`)));
await shot(p, "15-add-patient-form");
await b.close();
