import { BASE, browser, page, shot, text } from "./lib.mjs";
import { signIn, clickButton } from "./lib2.mjs";
const b = await browser();
const p = await page(b, "t");
await signIn(p, BASE, "yasmin@clinic.test", "walkthrough-therapist-1");
await p.goto(`${BASE}/patients/016f7f95-b109-4192-8fa3-0dd3dc972781`, { waitUntil: "networkidle" });
const t = await text(p);
console.log("--- patient record ---\n" + t.slice(0, 1600));
console.log("\nbuttons:", (await p.locator("button").allTextContents()).map(s=>s.trim()).filter(Boolean));
console.log("links:", await p.evaluate(() => [...document.querySelectorAll("a")].map(a=>a.getAttribute("href")).filter(h=>h&&!h.startsWith("/dashboard"))));
await shot(p, "18-patient-record");
await b.close();
