import { BASE, browser, page, shot, text } from "./lib.mjs";
import { clearLimits, clickButton } from "./lib2.mjs";
await clearLimits();
const b = await browser();
const p = await page(b, "patient");
await p.goto("http://localhost:3000/patient/invite/P10UHNmjg2XXFuwbZx1CngTu2-rU4mY7", { waitUntil: "networkidle" });
console.log("invite lands on:", p.url());
console.log((await text(p)).slice(0, 900));
await shot(p, "20-patient-invite");
console.log("fields:", await p.locator("input,select").evaluateAll(e => e.map(x => `${x.name || x.id}`)));
await b.close();
