import { BASE, browser, page, shot, text } from "./lib.mjs";
import { clearLimits, clickButton } from "./lib2.mjs";
await clearLimits();
const b = await browser();
const p = await page(b, "patient");
const TOKEN = "P10UHNmjg2XXFuwbZx1CngTu2-rU4mY7";
await p.goto(`${BASE}/patient/signup?invite=${TOKEN}`, { waitUntil: "networkidle" });
await p.fill("input[name=firstName]", "Mariam");
await p.fill("input[name=lastName]", "Saleh");
await p.fill("input[name=password]", "walkthrough-patient-1");
await clickButton(p, "Create account");
await p.waitForTimeout(3000);
console.log("url:", p.url());
console.log((await text(p)).slice(0, 900));
await shot(p, "22-patient-after-signup");
await b.close();
