import { BASE, browser, page, shot, text } from "./lib.mjs";
import { clearLimits, clickButton } from "./lib2.mjs";
await clearLimits();
const b = await browser();
const p = await page(b, "patient");
await p.goto(`${BASE}/patient/login`, { waitUntil: "networkidle" });
await p.fill("#handle", "+201001234567");
await p.fill("#password", "walkthrough-patient-1");
await p.click("button[type=submit]");
await p.waitForTimeout(2500);
await p.goto(`${BASE}/patient/claim`, { waitUntil: "networkidle" });
const t = await text(p);
console.log(t.slice(0, 700));
console.log("\ncards offered:", (t.match(/Is that you\?/g) || []).length);
await shot(p, "24-claim-suggestions");
await b.close();
