import { BASE, browser, page, shot, text } from "./lib.mjs";
import { clearLimits, clickButton } from "./lib2.mjs";
await clearLimits();
const b = await browser();
const p = await page(b, "patient");
await p.goto(`${BASE}/patient/login`, { waitUntil: "networkidle" });
await p.fill("#handle", "+201001234567");
await p.fill("#password", "walkthrough-patient-1");
await p.click("button[type=submit]");
await p.waitForTimeout(2500);
await p.goto(`${BASE}/patient/claim`, { waitUntil: "networkidle" });
await clickButton(p, "Yes, send me a code");
await p.waitForTimeout(2500);
console.log("--- after asking for a code ---");
console.log((await text(p)).slice(0, 900));
await shot(p, "25-claim-code");
await b.close();
