import { BASE, browser, page, shot, text } from "./lib.mjs";
import { signIn, clickButton } from "./lib2.mjs";
const b = await browser();
const p = await page(b, "t");
await signIn(p, BASE, "yasmin@clinic.test", "walkthrough-therapist-1");
const ROOM = "/sessions/c4b60d09-37fe-4c55-a530-c8b023d57a90/room";
await p.goto(`${BASE}${ROOM}`, { waitUntil: "networkidle" });
await clickButton(p, "End session");
await p.waitForTimeout(3000);
console.log("url:", p.url());
console.log((await text(p)).slice(0, 900));
console.log("buttons:", (await p.locator("button").allTextContents()).map(s=>s.trim()).filter(Boolean));
await shot(p, "31-session-ended");
await b.close();
