import { BASE, browser, page, shot, text } from "./lib.mjs";
import { signIn } from "./lib2.mjs";
const b = await browser();
const p = await page(b, "t");
await signIn(p, BASE, "yasmin@clinic.test", "walkthrough-therapist-1");
await p.goto(`${BASE}/sessions/c4b60d09-37fe-4c55-a530-c8b023d57a90`, { waitUntil: "networkidle" });
await p.waitForTimeout(2000);
console.log((await text(p)).slice(0, 1000));
await shot(p, "32-session-note-state");
await b.close();
