import { BASE, browser, page, shot, text } from "./lib.mjs";
import { signIn, clickButton } from "./lib2.mjs";
const b = await browser();
const p = await page(b, "t");
await signIn(p, BASE, "yasmin@clinic.test", "walkthrough-therapist-1");
await p.goto(`${BASE}/sessions/c4b60d09-37fe-4c55-a530-c8b023d57a90`, { waitUntil: "networkidle" });
await clickButton(p, "Sign the note");
await p.waitForTimeout(3000);
const t = await text(p);
console.log(t.slice(0, 700));
console.log("buttons:", (await p.locator("button").allTextContents()).map(s=>s.trim()).filter(Boolean));
await shot(p, "34-note-signed");
await b.close();
