import { BASE, browser, page, shot, text } from "./lib.mjs";
import { clearLimits } from "./lib2.mjs";
await clearLimits();
const b = await browser();
const p = await page(b, "patient");
await p.goto(`${BASE}/patient/login`, { waitUntil: "networkidle" });
await p.fill("#handle", "+201001234567");
await p.fill("#password", "walkthrough-patient-1");
await p.click("button[type=submit]");
await p.waitForTimeout(2500);
await p.goto(`${BASE}/patient?claimed=1`, { waitUntil: "networkidle" });
const t = await text(p);
console.log("--- with ?claimed=1 ---");
console.log(t.slice(0, 500));
await shot(p, "39-patient-home-claimed");
await p.goto(`${BASE}/patient`, { waitUntil: "networkidle" });
const t2 = await text(p);
console.log("\n--- plain /patient ---");
console.log(t2.slice(0, 400));
await b.close();
