/**
 * 🔴 80.1 — BUILDS `docs/VALUE-STATEMENTS.md` FROM `_value-statements.ts`.
 *
 *     npm run prove          # scripts/prove.ts, which writes what this returns
 *
 * The same argument as `npm run logins`: a list maintained by hand goes stale
 * the first time somebody edits one of the two copies, and the copy that drifts
 * is always the one a person reads rather than the one a script runs.
 *
 * Here the stakes are a little higher than a login table. This document is what
 * eight people are handed before they spend a day testing the product, and a
 * promise missing from it is a promise nobody checks. So the array is the
 * source, this turns it into prose, and `verify:prove` fails if the file on
 * disk is not what this would write.
 *
 * ## 🔴 WHY THIS IS A FILE WITH NO `main()` IN IT
 *
 * `_demo-cast.ts`'s header, exactly, and this earned it the same way. The first
 * draft of this was `prove.ts`, with the writer and the builder in one file,
 * guarded by `process.argv[1]?.endsWith("prove.ts")`. `verify-prove.ts`
 * imported `document()` from it to compare against the file on disk, and
 * `scripts/verify-prove.ts` ALSO ends with `prove.ts`, so the import rewrote
 * the document a moment before the check read it.
 *
 * The check could not fail. It reported `current` on a stale file, for ever,
 * and the whole point of it was to catch exactly that.
 *
 * So the builder lives here, where there is no `main()` and nothing to run, and
 * `prove.ts` is four lines that call it. The writer writes; the checker
 * compares; neither can start the other.
 *
 * ## 🔴 WHAT IT DELIBERATELY DOES NOT GENERATE
 *
 * `docs/PROVE-IT.md`, the walk. Ordering eight people across five positions is
 * judgement: who goes first, what the second person must not do until the first
 * has finished, where to stop and write something down. Generating it would
 * produce a list of steps with no argument in it. The gate holds the one
 * property that matters instead: every statement id appears in that document,
 * so a promise cannot be added here and left unwalked.
 */
import {
  AUDIENCES,
  SCENARIOS,
  TUNING,
  VALUE_STATEMENTS,
  type Audience,
} from "./_value-statements";
import { DEMO_LOGINS, DEMO_PASSWORD, isPrivateLogin } from "./_demo-cast";

/** Logins nothing can email, derived rather than counted by hand. */
const UNREACHABLE = DEMO_LOGINS.filter((l) => l.email.toLowerCase().endsWith("@example.com"));

export const VALUE_STATEMENTS_PATH = "docs/VALUE-STATEMENTS.md";

/** Which of the eight testers sits at each audience, in the founder's words. */
const TESTERS: Record<Audience, string> = {
  patient: "2 testers",
  therapist: "3 testers: one on pay as you go, two on clinic seats",
  clinic: "1 tester, the person who runs the practice",
  company: "1 tester, the person who funds the pot",
  admin: "1 tester, doing the work of all our staff",
};

export function document(): string[] {
  const lines: string[] = [
    "# What we promise, and what proves it",
    "",
    "🔴 **Generated by `npm run prove` from `scripts/_value-statements.ts`. Do not edit it by hand.**",
    "",
    `${String(VALUE_STATEMENTS.length)} promises, five per audience, and every one of them is a claim this`,
    "product already makes on a page a stranger can read or a rule it already enforces in code.",
    "Nothing here is new. `where` names the place we already say it, and that constraint is the",
    "whole point: a test plan written against invented promises proves a product nobody was sold.",
    "",
    "`docs/PROVE-IT.md` is the walk. This is the list it is walked against.",
    "",
    "## The two claims that may never appear here",
    "",
    "`lib/content/honesty.ts` refuses both at the door, in `savePage` and again against the",
    "published rows:",
    "",
    "1. **That paid sessions cover our fee.** At the prices this is actually sold at, fifteen per",
    "   cent of a twenty dollar session is three dollars against a four dollar fee. What is true is",
    "   netting, which is `T3`.",
    "2. **Any forecast of what a clinician will earn.** That is a prediction about somebody else's",
    "   business, and a clinician who moves practice on the strength of one has been misled by us.",
    "",
    "## How to read a row",
    "",
    "**Says** is the promise. **Where** is where we already make it. **Proof** is what has to be",
    "visible on a screen, to a person, for it to be kept. Not a row somebody could query: the",
    "whole reason eight people walk this rather than a verifier is that a verifier holds an",
    "invariant about a row and cannot tell you the screen above it does not say enough for",
    "somebody to act on.",
    "",
  ];

  for (const audience of AUDIENCES) {
    const mine = VALUE_STATEMENTS.filter((s) => s.audience === audience.id);
    lines.push(
      `## ${audience.who}`,
      "",
      `Signs in at \`${audience.signsInAt}\`. ${TESTERS[audience.id]}.`,
      "",
    );
    for (const statement of mine) {
      lines.push(
        `### ${statement.id} · ${statement.says}`,
        "",
        `**Where we say it.** ${statement.where}`,
        "",
        `**Proved when.** ${statement.proof}`,
        "",
      );
    }
  }

  lines.push(
    "## The five positions",
    "",
    "Each is a complete starting position rather than a change to the last one, so there is no",
    "order dependence between them and a half-finished walk cannot poison the next.",
    "",
    "```",
    "npm run on:production -- seed:demo -- --scenario=<name>",
    "npm run on:production -- verify:demo -- --scenario=<name>",
    "```",
    "",
    "| Position | What the database is put into | Proves | Edges from `04-THE-EDGES.md` |",
    "| --- | --- | --- | --- |",
    ...SCENARIOS.map(
      (s) =>
        `| \`${s.name}\` | ${s.title} | ${s.proves.join(", ")} | ${s.edges.join(", ")} |`,
    ),
    "",
  );

  for (const s of SCENARIOS) {
    const t = TUNING[s.name];
    lines.push(
      `### \`${s.name}\``,
      "",
      s.why,
      "",
      `The company covers **${String(t.coverageBps / 100)} per cent** and the pot was funded with ` +
        `**EGP ${(t.topUpCreditCents / 2).toLocaleString("en-US")}** ($${String(t.topUpCreditCents / 100)} at 50 to the dollar)` +
        (t.welcomeCreditCents > 0 ? `, on top of a $${String(t.welcomeCreditCents / 100)} welcome credit. ` : ", with no welcome credit. ") +
        (t.enrolTheSecondPatient
          ? "Two people are on that pot."
          : "One person is on that pot, and one patient is enrolled nowhere."),
      "",
    );
  }

  lines.push(
    "## Everyone you sign in as",
    "",
    "One password for every patient, clinician and the clinic:",
    "",
    "    " + DEMO_PASSWORD,
    "",
    "🔴 **The three marked private never take it**: the repository is public and they open the",
    "production console and a company's money. Their password is `DEMO_PRIVATE_PASSWORD` in the",
    "operator's own `.env.local`, never committed. `docs/DEMO-CAST.md` says more.",
    "",
    "| Who | Sign-in page | Address |",
    "| --- | --- | --- |",
    ...DEMO_LOGINS.map(
      (l) =>
        `| ${l.who}${isPrivateLogin(l.email) ? " (private password)" : ""} | \`${l.where}\` | \`${l.email}\` |`,
    ),
    "",
    `🔴 **${String(UNREACHABLE.length)} of these are at \`example.com\` and cannot receive email:** ` +
      `${UNREACHABLE.map((l) => `\`${l.email}\``).join(", ")}.`,
    "They sign in like everybody else, and anything the product would have",
    "emailed them goes nowhere. That is deliberate, because RFC 2606 reserves the domain so a",
    "message that escapes a test reaches nobody, and it means **the email half of any promise must be",
    "walked on one of the five real inboxes**, never on those three. `P2` is written to be",
    "provable inside the app for exactly this reason.",
    "",
  );

  return lines;
}

/** For the writer's own output line, and for the gate's failure message. */
export const COUNTS = {
  promises: VALUE_STATEMENTS.length,
  positions: SCENARIOS.length,
};
