/**
 * Every lifecycle in the product, written down where a person can read it.
 *
 *     npm run lifecycles           # print
 *     npm run lifecycles -- --write  # …and write docs/LIFECYCLES.md
 *
 * ## Why this exists next to the gate
 *
 * `verify:machines` proves the eleven machines hold together. It does not show
 * them to anybody, and the whole argument for declaring them was that an edge
 * case is a missing arrow and the only way to SEE a missing arrow is to look
 * at the ones that exist. A machine only a script reads is a type declaration.
 *
 * So this renders the same data as tables, and the two tables that matter are
 * the last two: every place a person is stopped, and every promise we have
 * made about how long a wait lasts. Those are the register and the clock, and
 * they are derived rather than maintained, which is the only way they stay
 * true.
 */
import { writeFileSync } from "node:fs";
import { MACHINES, type Kind } from "../lib/lifecycle/machines";

const SHAPE: Record<Kind, string> = {
  working: "in flight",
  resting: "resting",
  success: "finished",
  blocked: "STOPPED, can still move",
  "dead-end": "STOPPED, this one is over",
};

function render(): string {
  const out: string[] = [];
  out.push("# Every lifecycle in the product");
  out.push("");
  out.push(
    "Generated by `npm run lifecycles -- --write`. Do not edit by hand: it is " +
      "derived from `lib/lifecycle/machines.ts`, which `verify:machines` holds " +
      "against `lib/db/schema.ts` and against the real route list.",
  );
  out.push("");

  const states = MACHINES.reduce((n, m) => n + Object.keys(m.states).length, 0);
  const arrows = MACHINES.reduce((n, m) => n + m.transitions.length, 0);
  out.push(
    `**${String(MACHINES.length)} lifecycles · ${String(states)} states · ` +
      `${String(arrows)} transitions**`,
  );
  out.push("");
  out.push("---");
  out.push("");

  for (const m of MACHINES) {
    out.push(`## ${m.key}`);
    out.push("");
    out.push(`Table \`${m.entity}\`. Starts at **${m.initial}**.`);
    out.push("");
    out.push("| State | What it is | Seen on | For how long |");
    out.push("| --- | --- | --- | --- |");
    for (const [name, spec] of Object.entries(m.states)) {
      out.push(
        `| \`${name}\` | ${SHAPE[spec.kind]} | ${spec.screen} | ${spec.promise ?? "not a wait"} |`,
      );
    }
    out.push("");
    out.push("| From | To | What does it | Who |");
    out.push("| --- | --- | --- | --- |");
    for (const t of m.transitions) {
      out.push(`| \`${t.from}\` | \`${t.to}\` | ${t.trigger} | ${t.by} |`);
    }
    out.push("");
  }

  /*
   * 🔴 THE TWO TABLES THE ROUND-THE-CLOCK DESK ACTUALLY WORKS FROM.
   *
   * Everything above is reference. These two are the job: who is stopped, and
   * what we said we would do about it. They are last because a reader who
   * scrolls to the bottom of a long document should land on the part that is
   * about people rather than about rows.
   */
  out.push("---");
  out.push("");
  out.push("## Every way a person is stopped");
  out.push("");
  out.push(
    "This is the register. `STOPPED, can still move` is the one to watch: the " +
      "person is blocked and the row has not ended, so whether they are stuck " +
      "or merely delayed depends entirely on who owns the way out.",
  );
  out.push("");
  out.push("| Lifecycle | State | Which | What they can do | Who holds the key |");
  out.push("| --- | --- | --- | --- | --- |");
  for (const m of MACHINES) {
    for (const [name, spec] of Object.entries(m.states)) {
      if (spec.kind !== "blocked" && spec.kind !== "dead-end") continue;
      const out2 = m.transitions.filter((t) => t.from === name);
      const keys = out2.length === 0 ? "nobody, it is over" : [...new Set(out2.map((t) => t.by))].join(", ");
      out.push(
        `| ${m.key} | \`${name}\` | ${SHAPE[spec.kind]} | ${spec.exit ?? "**NOTHING, and that is a defect**"} | ${keys} |`,
      );
    }
  }
  out.push("");

  out.push("## Every promise we have made");
  out.push("");
  out.push(
    "A promise is how long a state may last before somebody must act. Task " +
      "#166 alerts on the AGE of the oldest row in each of these, never on the " +
      "count, because a queue of two that has been waiting a week is the " +
      "problem and a queue of two hundred cleared hourly is not.",
  );
  out.push("");
  /*
   * 🔴 AND WHICH OF THEM A CLOCK CAN ACTUALLY COUNT.
   *
   * "2 working days" is a promise. "until the employer answers" is a hope: it
   * names no span, so nothing can age past it and #166 has nothing to fire on.
   * The test below is a heuristic and is presented as one, in a document, not
   * as a gate: it looks for a number or a span of time. It is here so that the
   * ones with no clock behind them are VISIBLE while #166 is being built,
   * rather than discovered when the first company waits a fortnight.
   */
  const measurable = /\b(\d+|minutes?|hours?|days?|weeks?|window|allowance|starts|expir|life of)\b/i;
  out.push("| Lifecycle | State | Promise | A clock can count it |");
  out.push("| --- | --- | --- | --- |");
  for (const m of MACHINES) {
    for (const [name, spec] of Object.entries(m.states)) {
      if (!spec.promise) continue;
      const ok = measurable.test(spec.promise);
      out.push(
        `| ${m.key} | \`${name}\` | ${spec.promise} | ${ok ? "yes" : "**no, and #166 needs one**"} |`,
      );
    }
  }
  out.push("");

  return out.join("\n");
}

function main() {
  const text = render();
  if (process.argv.includes("--write")) {
    writeFileSync("docs/LIFECYCLES.md", `${text}\n`);
    console.log("wrote docs/LIFECYCLES.md");
  } else {
    console.log(text);
  }

  const stopped = MACHINES.flatMap((m) =>
    Object.values(m.states).filter((s) => s.kind === "blocked" || s.kind === "dead-end"),
  );
  const promises = MACHINES.flatMap((m) =>
    Object.values(m.states).filter((s) => s.promise),
  );
  console.log(
    `${String(MACHINES.length)} lifecycles · ` +
      `${String(stopped.length)} ways to be stopped · ` +
      `${String(promises.length)} promises`,
  );
}

main();
