/**
 * 🔴 76.54 — WRITES `docs/simulation/12-THE-LOGINS.md` FROM `scripts/_cast.ts`.
 *
 *     npm run logins
 *
 * ## Why this is generated
 *
 * The run leaves six months of records on production and nothing deletes them,
 * so the document that says how to sign in as each person is the document that
 * makes the whole run readable afterwards. A login list maintained by hand goes
 * stale the first time somebody renames a cast member, and you find out which
 * two rows are wrong while trying to open a record.
 *
 * `_cast.ts` is the one list. `verify:cast` checks it against the database and
 * checks the password actually works. This turns it into prose. All three read
 * the same array, so they cannot disagree.
 *
 * ## 🔴 THE PASSWORD IS IN THE FILE, AND THAT IS FINE HERE AND NOWHERE ELSE
 *
 * `Simulation2026!` opens twenty six invented accounts belonging to nobody, on a
 * database whose keys are rotated the day the run ends. It is written down
 * because a founder who cannot get in cannot read the thing this was all for.
 *
 * The day a real person signs up, this document describes accounts that must be
 * deleted rather than accounts somebody may sign into, and `08-THE-END.md` says
 * so. That is a different document's job and it is not softened here.
 */
import { writeFileSync } from "node:fs";

import { CAST, PAYROLL, SIMULATION_PASSWORD, WITH_LOGINS } from "./_cast";

const PATH = "docs/simulation/12-THE-LOGINS.md";

function main(): void {
  const waves = [...new Set(CAST.map((person) => person.wave))].sort();

  const lines: string[] = [
    "# Signing in as every person in the run",
    "",
    "🔴 **Generated by `npm run logins` from `scripts/_cast.ts`. Do not edit it by hand.**",
    "",
    "The six months of records stay on the production database when the run ends. They are",
    "not deleted and not restored away, so every person below can be signed in as, and their",
    "record read, for as long as the data is kept.",
    "",
    "One password for all of them:",
    "",
    "    " + SIMULATION_PASSWORD,
    "",
    "A clinician's, a manager's, an employer's and a developer's address is always their own",
    "name: `<first name>.<surname>@example.com`, lower case. **A patient's is a phone number.**",
    "`npm run on:production -- verify:cast` reads every one of them back out of the",
    "database and checks the password actually opens it, which is a different fact from the",
    "row existing and the one that goes wrong.",
    "",
    "## Where to sign in",
    "",
    "| Who | Sign-in page | Lands on |",
    "| --- | --- | --- |",
    "| Operator and staff | `/staff/sign-in` | `/admin` |",
    "| Therapists | `/login` | `/dashboard` |",
    "| Patients | `/patient/login` | `/patient` |",
    "| Practice manager and practice staff | `/clinic/sign-in` | `/clinic` |",
    "| Employers | `/sponsor/sign-in` | `/sponsor` |",
    "| The partner's developer | `/partner/sign-in` | `/partner` |",
    "",
    "🔴 **A PATIENT SIGNS IN WITH HER PHONE NUMBER, NOT AN ADDRESS.** `/patient/signup` asks for",
    "a first name, a phone, a time zone and an optional password, and **it never asks for an",
    "email**. Nothing anywhere else lets her add one either: `/patient/account` shows the address",
    "as \"not added\" beside a notice calling it *\"another way to sign in, and the only way to",
    "receive your record\"*, and offers no control to add it.",
    "",
    "So `patient_accounts.email` is null for every patient in this run, the handle is the number",
    "in the block `01-THE-CAST.md` reserved, and the way in is a one-time code rather than the",
    "shared password. The mini simulation found this by being refused at the form; before that,",
    "this document promised seven addresses and `verify:cast --complete` would have reported",
    "seven people missing at the end of six months.",
    "",
    "🔴 **Six doors, because there are six principals.** A therapist's cookie cannot become a",
    "patient's, a clinic manager's, a sponsor admin's or a partner's: different tables, different",
    "cookies, different guards. Signing in at the wrong one of these does not fail with a",
    "password error, it fails with an account that does not exist, and that is the boundary",
    "working rather than a typo.",
    "",
  ];

  for (const wave of waves) {
    lines.push(`## Wave ${String(wave)}`, "", "| Key | Who | Sign in as | Arrives | What their record holds |", "| --- | --- | --- | --- | --- |");

    for (const person of CAST.filter((p) => p.wave === wave)) {
      /*
       * 🔴 A PATIENT'S HANDLE IS HER PHONE, and this column used to promise
       * seven addresses that cannot exist. `/patient/signup` never asks for an
       * email and no screen lets her add one, so what goes here for a patient
       * is the number she actually signed up with.
       */
      const handle = person.phone
        ? `\`${person.phone}\` **and a code**`
        : (person.email ?? "**no account, ever**");
      lines.push(
        `| \`${person.key}\` | ${person.name} | ${handle} | ${person.arrives} | ${person.record} |`,
      );
    }
    lines.push("");
  }

  lines.push(
    "## The one with no login",
    "",
    "`P6` Ziad Example never creates an account. He sees a therapist three times through join",
    "links and stays a stranger to us. His record is reachable from his clinician's side and",
    "from nowhere else, and that is the product working rather than a gap in this table.",
    "`verify:cast` fails if an account for him ever appears.",
    "",
    "## Our own payroll, and which queue each of them works",
    "",
    "🔴 **All seven can sign in, which they could not before 76.55.** The payroll held seven",
    "people and only two of them had an account, so five colleagues drew $500 a month for six",
    "months and every row they were meant to clear would have been cleared by the operator.",
    "An audit log in which one person did everything is not evidence about a company of seven.",
    "",
    "| Who | Sign in as | Role | The queue that is theirs |",
    "| --- | --- | --- | --- |",
  );

  for (const person of PAYROLL) {
    lines.push(
      `| ${person.name} | ${person.email!} | \`${person.payroll.role}\` | ${person.payroll.queue} |`,
    );
  }

  lines.push(
    "",
    "The two founders are `super_admin` and the other five are `staff`, and the difference is",
    "load bearing: `/admin/benefits`, `/admin/radar`, `/admin/actuals`, the board and the error",
    "log are founder-only, and a support person opening one of them is redirected. **Capture that",
    "redirect.** A permission nobody was ever refused by is a permission nobody has tested.",
    "",
    "## How many people this is",
    "",
    `| The cast, one agent each | ${String(CAST.length - PAYROLL.length)} |`,
    "| --- | --- |",
    `| Our own payroll, worked by the standing agents | ${String(PAYROLL.length)} |`,
    `| **People in the run** | **${String(CAST.length)}** |`,
    `| **Accounts that must open with the password** | **${String(WITH_LOGINS.length)}** |`,
    "",
    "`01-THE-CAST.md` names the same total in its own table and `verify:cast` reads it out of",
    "that file and fails if the two disagree, because the version of this document that said",
    "eighteen while the code held four fewer people is how `T5`, `T6`, `P7` and `D1` went a",
    "sprint without an address anybody could sign in with.",
    "",
  );

  writeFileSync(PATH, lines.join("\n"));
  console.log(`\n  ${PATH}: ${String(CAST.length)} people, ${String(waves.length)} waves.\n`);
}

main();
