/**
 * 🔴 52.1 / C225 — THE CAST FOR THE WALKTHROUGH AND THE FILMS. ONE SEEDED RUN, SIX PRINCIPALS.
 *
 *   DATABASE_URL='…' node --import tsx --conditions=react-server scripts/seed-capture.ts
 *
 * Run AFTER `reset.ts --i-mean-it --demo`, which empties the database and lays down the
 * organisation, the settings, the content and the therapist-and-patient pair. This adds the four
 * principals that pair has never had: a sponsor, a clinic, a partner, and the cross-portal flows
 * C268 named after sprint 52 was written.
 *
 * ## 🔴 C225 DECIDES THE NAMES, AND IT COSTS SOMETHING
 *
 * > *Synthetic people only, generated by the seed, with names that cannot be mistaken for real
 * > ones, and the entire capture runs against a freshly purged database.*
 *
 * A promo film wants names that look like people. C225 wants names that CANNOT be mistaken for
 * people. Those pull in opposite directions and the ruling wins, because the cost of getting it
 * wrong is unrecallable: *a single real name in one frame of a marketing video is a disclosure that
 * cannot be recalled.*
 *
 * So every person here has the surname **Demo** or **Example**, every email is at `example.com`
 * (reserved for documentation by RFC 2606, so it can never reach a real inbox), and every phone
 * number is in one obviously-sequential block. A frame containing "Layla Demo" is a frame anybody
 * can see is synthetic without checking. `verify:sprint52` asserts it: every person in the database
 * carries one of those two surnames, with a planted control.
 *
 * 🔴 The forenames are ordinary Arabic and English ones on purpose. The films are in two languages
 * and a cast called "Patient A" would make the Arabic cut read as a wireframe. An ordinary forename
 * with an unmistakable surname is the line that satisfies both.
 *
 * ## 🔴 AND IT REFUSES TO RUN ANYWHERE BUT THE CAPTURE BRANCH
 *
 * `writesTo()` from `scripts/_verify.ts` refuses production by name and prints the host either way.
 * This adds a second condition that the other direction: it refuses anything that is NOT the
 * capture endpoint, because a cast of invented therapists on the verification branch would show up
 * on somebody's next walkthrough and be mistaken for real state.
 */
import { sql } from "drizzle-orm";

import { connect } from "./db";
import { hashPassword } from "../lib/auth/password";

/** 🔴 The one endpoint this may write to. Not a prefix match on "not production". */
const CAPTURE_ENDPOINT = "ep-little-sky-a6v9sdx4";
const PRODUCTION_ENDPOINT = "ep-wild-lake-a6tgm2r6";

/** One password for every synthetic account, so a walkthrough is not a key-management exercise. */
const PASSWORD = "CaptureRun2026!";

/**
 * 🔴 The cast. Every surname is Demo or Example, every address is at example.com.
 *
 * The shape is a table rather than prose so `verify:sprint52` can read it and so the walkthrough
 * script has one place to look up who signs in where.
 */
export const CAST = {
  /* The therapist `reset.ts --demo` already made, renamed here so the whole cast is consistent. */
  therapist: { email: "test@24therapy.ai", password: "TestTherapist2026!", name: "Test Therapist" },

  clinicManager: { email: "manager@example.com", password: PASSWORD, name: "Hana Example" },
  clinicClinician: { email: "clinician@example.com", password: PASSWORD, name: "Tarek Example" },

  sponsorUser: { email: "hr@example.com", password: PASSWORD, name: "Dalia Example" },
  partnerUser: { email: "dev@example.com", password: PASSWORD, name: "Omar Example" },

  sponsoredPatient: { name: "Layla Demo", phone: "+201300052001" },
  clinicPatient: { name: "Youssef Demo", phone: "+201300052002" },
  partnerPatient: { name: "Mariam Demo", phone: "+201300052003" },
} as const;

async function main() {
  const url = process.env.DATABASE_URL ?? "";
  const host = url.match(/@([^/:?]+)/)?.[1] ?? "(none)";

  console.log(`writing to ${host}\n`);

  if (host.includes(PRODUCTION_ENDPOINT)) {
    console.error("Refusing to run: that is production.");
    process.exit(1);
  }
  if (!host.includes(CAPTURE_ENDPOINT)) {
    console.error(
      `Refusing to run: this seed is for the capture branch only (${CAPTURE_ENDPOINT}).\n` +
        "A cast of invented therapists on any other branch will be mistaken for real state.",
    );
    process.exit(1);
  }

  const { pool, db } = connect();

  try {
    const hash = await hashPassword(PASSWORD);

    /*
     * 🔴 IT OWNS ITS OWN ROWS AND CLEARS THEM FIRST, so a second run is a clean run.
     *
     * The first version was not idempotent, and the first thing that happened was a partial run: it
     * created the sponsor, failed on the next statement, and then refused to start again because
     * `sponsor_users_email_unique` already held `hr@example.com`. A seed that can only be run once
     * is a seed that has to be preceded by a full purge every time, and 52.1 says the walkthrough and
     * the capture share ONE seeded run — which means re-running this after a fix must not require
     * re-purging and re-seeding everything else.
     *
     * Deleting by the cast's own markers rather than truncating, because `reset.ts` already did the
     * truncating and this must not undo the therapist, patient and session it seeded.
     */
    /*
     * 🔴 CHILDREN FIRST, AND 0082 IS WHY THE ORDER IS SPELLED OUT RATHER THAN GUESSED.
     *
     * The first version deleted `partners` before the `organizations` that reference it. Until 0082
     * that "worked", because the foreign key was ON DELETE SET NULL and silently nulled
     * `organizations.partner_id` — which then violated
     * `organizations_partner_billed_names_partner` and failed with an error naming a table this
     * script was not touching. With 0082's RESTRICT the same mistake fails immediately and says
     * exactly which constraint refused, which is the whole argument for RESTRICT over SET NULL.
     *
     * `organizations` therefore goes before `partners`, and `patients` before `people`.
     */
    for (const statement of [
      sql`DELETE FROM enrolments WHERE person_id IN (SELECT id FROM people WHERE last_name = 'Demo')`,
      sql`DELETE FROM ledger_entries WHERE ref_type = 'sponsor'`,
      sql`DELETE FROM sponsor_users WHERE email LIKE '%@example.com'`,
      sql`DELETE FROM patients WHERE last_name = 'Demo'`,
      sql`DELETE FROM people WHERE last_name = 'Demo'`,
      sql`DELETE FROM clinic_managers WHERE email LIKE '%@example.com'`,
      sql`DELETE FROM subscriptions WHERE organization_id IN
            (SELECT id FROM organizations WHERE slug IN ('demo-clinic', 'demo-health-clinicians'))`,
      sql`DELETE FROM users WHERE email LIKE '%@example.com' AND role = 'therapist'`,
      /* 🔴 Before `partners`, per the block above. */
      sql`DELETE FROM organizations WHERE slug IN ('demo-clinic', 'demo-health-clinicians')`,
      sql`DELETE FROM partner_users WHERE email LIKE '%@example.com'`,
      sql`DELETE FROM partners WHERE slug = 'demo-health'`,
      sql`DELETE FROM sponsors WHERE name = 'Demo Holdings'`,
    ]) {
      await db.execute(statement);
    }

    /* The organisation `reset.ts` seeded, and the therapist under it. */
    const [{ id: soloOrgId }] = (
      await db.execute(sql`SELECT id FROM organizations WHERE slug = '24therapy' LIMIT 1`)
    ).rows as { id: string }[];

    const [{ id: therapistId }] = (
      await db.execute(
        sql`SELECT id FROM users WHERE email = ${CAST.therapist.email} LIMIT 1`,
      )
    ).rows as { id: string }[];

    console.log(`solo org ${soloOrgId}, therapist ${therapistId}`);

    /* ================================================================ */
    /*  The sponsor — 53. A company funding therapy nobody pays for.     */
    /* ================================================================ */

    const [sponsor] = (
      await db.execute(sql`
      INSERT INTO sponsors (name, kind, state, entity, currency, listed_publicly)
      VALUES ('Demo Holdings', 'company', 'active', 'us', 'usd', true)
      RETURNING id`)
    ).rows as { id: string }[];

    await db.execute(sql`
      INSERT INTO sponsor_users (sponsor_id, email, name, password_hash, role)
      VALUES (${sponsor.id}, ${CAST.sponsorUser.email}, ${CAST.sponsorUser.name}, ${hash}, 'admin')`);

    /*
     * 🔴 A funded pot, so the film can show a session the patient never pays for.
     *
     * The ledger sign convention: `sponsor_pot` is a LIABILITY, so a top-up is NEGATIVE and a spend
     * is positive. Getting this backwards is the sprint-53 bug the founder called the sharpest
     * finding in that report, and seeding it backwards would put a chart in a film showing every
     * deposit as expenditure.
     */
    await db.execute(sql`
      INSERT INTO ledger_entries (organization_id, account, amount_cents, currency, entity, txn_kind,
                                  ref_type, ref_id, txn_id, memo)
      VALUES (${soloOrgId}, 'sponsor_pot', -500000, 'usd', 'us', 'pot_topup',
              'sponsor', ${sponsor.id}, gen_random_uuid(), 'Demo Holdings opening balance')`);

    console.log(`sponsor: Demo Holdings, ${CAST.sponsorUser.email}`);

    /* ================================================================ */
    /*  The clinic — 54. An organisation with a manager and clinicians.  */
    /* ================================================================ */

    const [clinic] = (
      await db.execute(sql`
      INSERT INTO organizations (name, slug, kind, clinic_state, contact_name, contact_email,
                                 contact_phone)
      VALUES ('Demo Clinic', 'demo-clinic', 'clinic', 'active', ${CAST.clinicManager.name},
              ${CAST.clinicManager.email}, '+201300052100')
      RETURNING id`)
    ).rows as { id: string }[];

    await db.execute(sql`
      INSERT INTO subscriptions (organization_id, plan, status)
      VALUES (${clinic.id}, 'payg', 'active')`);

    await db.execute(sql`
      INSERT INTO clinic_managers (organization_id, email, name, password_hash, role)
      VALUES (${clinic.id}, ${CAST.clinicManager.email}, ${CAST.clinicManager.name}, ${hash},
              'admin')`);

    /* A verified clinician inside the clinic, so the clinic's schedule has a name on it. */
    const [clinicClinician] = (
      await db.execute(sql`
      INSERT INTO users (organization_id, email, first_name, last_name, role, verification_status,
                         password_hash, profile)
      VALUES (${clinic.id}, ${CAST.clinicClinician.email}, 'Tarek', 'Example', 'therapist',
              'verified', ${hash},
              '{"credentials":"MSc Clinical Psychology","licenseState":"EG","timezone":"Africa/Cairo"}'::jsonb)
      RETURNING id`)
    ).rows as { id: string }[];

    console.log(`clinic: Demo Clinic, ${CAST.clinicManager.email} + ${CAST.clinicClinician.email}`);

    /* ================================================================ */
    /*  The partner — 55. A platform whose clinician we can launch.      */
    /* ================================================================ */

    const [partner] = (
      await db.execute(sql`
      INSERT INTO partners (name, slug, state, contact_name, contact_email, contact_phone, intent)
      VALUES ('Demo Health Platform', 'demo-health', 'active', ${CAST.partnerUser.name},
              ${CAST.partnerUser.email}, '+201300052200',
              'Employment verification for our HR product, and session writeback from our own video.')
      RETURNING id`)
    ).rows as { id: string }[];

    await db.execute(sql`
      INSERT INTO partner_users (partner_id, email, name, password_hash, role)
      VALUES (${partner.id}, ${CAST.partnerUser.email}, ${CAST.partnerUser.name}, ${hash}, 'admin')`);

    /*
     * 🔴 A partner-billed organisation, which is what makes 55.9's launch possible.
     *
     * `launchClinician` requires `organizations.partner_id` with `billing_mode = 'partner_billed'`
     * — the association whose absence was the worst defect in sprint 55. Without it here, the
     * split-screen film's "a partner's call landing in a chart" cannot be walked at all.
     */
    const [partnerOrg] = (
      await db.execute(sql`
      INSERT INTO organizations (name, slug, kind, partner_id, billing_mode)
      VALUES ('Demo Health Clinicians', 'demo-health-clinicians', 'solo', ${partner.id},
              'partner_billed')
      RETURNING id`)
    ).rows as { id: string }[];

    await db.execute(sql`
      INSERT INTO subscriptions (organization_id, plan, status)
      VALUES (${partnerOrg.id}, 'payg', 'active')`);

    const [partnerClinician] = (
      await db.execute(sql`
      INSERT INTO users (organization_id, email, first_name, last_name, role, verification_status,
                         password_hash, profile)
      VALUES (${partnerOrg.id}, 'partner.clinician@example.com', 'Sara', 'Example', 'therapist',
              'verified', ${hash},
              '{"credentials":"MD Psychiatry","licenseState":"EG","timezone":"Africa/Cairo"}'::jsonb)
      RETURNING id`)
    ).rows as { id: string }[];

    console.log(`partner: Demo Health Platform, ${CAST.partnerUser.email}`);

    /* ================================================================ */
    /*  The patients, one per cross-portal flow (C268)                   */
    /* ================================================================ */

    for (const [who, orgId, clinicianId, forename] of [
      ["sponsoredPatient", soloOrgId, therapistId, "Layla"],
      ["clinicPatient", clinic.id, clinicClinician.id, "Youssef"],
      ["partnerPatient", partnerOrg.id, partnerClinician.id, "Mariam"],
    ] as const) {
      const person = CAST[who];

      const [created] = (
        await db.execute(sql`
        INSERT INTO patients (organization_id, therapist_id, first_name, last_name, phone, source)
        VALUES (${orgId}, ${clinicianId}, ${forename}, 'Demo', ${person.phone}, 'therapist')
        RETURNING id`)
      ).rows as { id: string }[];

      /*
       * 🔴 5.1 — every patient gets a PERSON, and the seed must do it explicitly.
       *
       * `ensurePersonForPatient` runs inside `createPatient`, which this does not use because a
       * seed has no `Actor`. A patient with no person row would leave the check-in channel and
       * Total View with nothing to join on, which would read as those features being broken in a
       * film rather than as a seed being incomplete.
       */
      await db.execute(sql`
        INSERT INTO people (first_name, last_name, phone, region)
        VALUES (${forename}, 'Demo', ${person.phone}, 'us')`);

      await db.execute(sql`
        UPDATE patients SET person_id = (SELECT id FROM people WHERE phone = ${person.phone})
         WHERE id = ${created.id}`);

      console.log(`patient: ${person.name} (${person.phone})`);
    }

    /*
     * 🔴 Layla is ENROLLED with the sponsor, which is what makes "a session the patient never pays
     * for" walkable. The identifier is hashed, as 53.20 requires: a stolen table is not a list of
     * work addresses.
     */
    await db.execute(sql`
      INSERT INTO enrolments (sponsor_id, person_id, identifier_hash, identifier_kind, state,
                             last_verified_at)
      VALUES (${sponsor.id},
              (SELECT id FROM people WHERE phone = ${CAST.sponsoredPatient.phone}),
              encode(sha256('capture:layla@example.com'::bytea), 'hex'),
              'domain_email', 'active', now())`);

    console.log("\nDone. Six principals, one seeded run.");
    console.log(`\npassword for every synthetic account: ${PASSWORD}`);
  } finally {
    await pool.end();
  }
}

void main();
