/**
 * 🔴 52.1 / C225 — THE CAST FOR THE WALKTHROUGH AND THE FILMS. ONE SEEDED RUN, SIX PRINCIPALS.
 *
 *   DATABASE_URL='…' node --import tsx --conditions=react-server scripts/seed-capture.ts
 *
 * Run AFTER `reset.ts --i-mean-it --demo`, which empties the database and lays down the
 * organisation, the settings, the content and the therapist-and-patient pair. This adds the four
 * principals that pair has never had: a sponsor, a clinic, a partner, and the cross-portal flows
 * C268 named after sprint 52 was written.
 *
 * ## 🔴 C225 DECIDES THE NAMES, AND IT COSTS SOMETHING
 *
 * > *Synthetic people only, generated by the seed, with names that cannot be mistaken for real
 * > ones, and the entire capture runs against a freshly purged database.*
 *
 * A promo film wants names that look like people. C225 wants names that CANNOT be mistaken for
 * people. Those pull in opposite directions and the ruling wins, because the cost of getting it
 * wrong is unrecallable: *a single real name in one frame of a marketing video is a disclosure that
 * cannot be recalled.*
 *
 * So every person here has the surname **Demo** or **Example**, every email is at `example.com`
 * (reserved for documentation by RFC 2606, so it can never reach a real inbox), and every phone
 * number is in one obviously-sequential block. A frame containing "Layla Demo" is a frame anybody
 * can see is synthetic without checking. `verify:sprint52` asserts it: every person in the database
 * carries one of those two surnames, with a planted control.
 *
 * 🔴 The forenames are ordinary Arabic and English ones on purpose. The films are in two languages
 * and a cast called "Patient A" would make the Arabic cut read as a wireframe. An ordinary forename
 * with an unmistakable surname is the line that satisfies both.
 *
 * ## 🔴 AND IT REFUSES TO RUN ANYWHERE BUT THE CAPTURE BRANCH
 *
 * `writesTo()` from `scripts/_verify.ts` refuses production by name and prints the host either way.
 * This adds a second condition that the other direction: it refuses anything that is NOT the
 * capture endpoint, because a cast of invented therapists on the verification branch would show up
 * on somebody's next walkthrough and be mistaken for real state.
 */
import { sql } from "drizzle-orm";

import { connect } from "./db";
import { required } from "./_verify";
import { hashPassword } from "../lib/auth/password";

/** 🔴 The one endpoint this may write to. Not a prefix match on "not production". */
const CAPTURE_ENDPOINT = "ep-little-sky-a6v9sdx4";
const PRODUCTION_ENDPOINT = "ep-wild-lake-a6tgm2r6";

/** One password for every synthetic account, so a walkthrough is not a key-management exercise. */
const PASSWORD = "CaptureRun2026!";

/**
 * 🔴 The cast. Every surname is Demo or Example, every address is at example.com.
 *
 * The shape is a table rather than prose so `verify:sprint52` can read it and so the walkthrough
 * script has one place to look up who signs in where.
 */
export const CAST = {
  /* The therapist `reset.ts --demo` already made, renamed here so the whole cast is consistent. */
  therapist: { email: "test@24therapy.app", password: "TestTherapist2026!", name: "Test Therapist" },

  /*
   * 🔴 The super admin `reset.ts --demo` made, whose password came from an env var nobody wrote
   * down. One of the four cuts is the admin console, and a console nobody can open is a cut that
   * cannot be shot. Reset to the cast password below, which is safe here and nowhere else: this
   * script refuses to run anywhere but the capture endpoint.
   */
  admin: { email: "admin@example.com", password: PASSWORD, name: "Super Admin" },

  clinicManager: { email: "manager@example.com", password: PASSWORD, name: "Hana Example" },
  clinicClinician: { email: "clinician@example.com", password: PASSWORD, name: "Tarek Example" },

  sponsorUser: { email: "hr@example.com", password: PASSWORD, name: "Dalia Example" },
  partnerUser: { email: "dev@example.com", password: PASSWORD, name: "Omar Example" },

  /*
   * 🔴 THE PATIENTS SIGN IN, AND THE FIRST VERSION OF THIS SEED DID NOT LET THEM.
   *
   * 52.3's findings walk found it before a frame was captured: `patient_accounts` held ZERO rows,
   * so `/patient/login` could be photographed and nothing behind it could. The patient portal is the
   * portal this product is judged on — it is what 37R.8 asks about and what the first of the four
   * cuts is made of — and a cast with no way into it makes both of those unanswerable.
   *
   * The record and the account are different things here, which is sprint 6's whole design: a
   * `patients` row is what a clinician wrote down, a `patient_accounts` row is a person with a
   * password, and `people.claimed_at` is the moment the second took over the first. A seed that
   * creates only the first is a seed that models a product where nobody ever signs in.
   */
  sponsoredPatient: {
    name: "Layla Demo",
    phone: "+201300052001",
    email: "layla.demo@example.com",
    password: PASSWORD,
  },
  clinicPatient: {
    name: "Youssef Demo",
    phone: "+201300052002",
    email: "youssef.demo@example.com",
    password: PASSWORD,
  },
  partnerPatient: {
    name: "Mariam Demo",
    phone: "+201300052003",
    email: "mariam.demo@example.com",
    password: PASSWORD,
  },
} as const;

/**
 * 🔴 The note the film shows, in the shape the product actually stores.
 *
 * `session_notes.content` is structured rather than prose, and that structure IS sprint 47: the
 * clinician's SOAP note and the patient's brief are different fields written in the same pass,
 * because "sending the professional document to the person it is about is how a clinician ends up
 * explaining the word guarded over the phone".
 *
 * So a seeded blob of SOAP text would have filmed the wrong thing twice over: it would not render,
 * and it would have hidden the one decision the sprint was about. Both halves are written here, and
 * they say different things about the same fifty minutes on purpose — `impressions` carries clinical
 * language ("self-criticism on display") that `patientBrief` deliberately does not.
 *
 * C225: invented, ordinary, and belonging to nobody. See the note on the content section.
 */
const NOTE = {
  "soap": {
    "subjective": "Reports a one-week return of middle-insomnia, waking around 03:00 with ruminative thinking focused on a work review that was brought forward. Describes a loop between daytime fatigue and anticipatory worry. Partial adherence to the agreed wind-down routine, four nights of seven, with subjectively faster return to sleep on those nights.",
    "objective": "Alert and engaged throughout. Affect mildly constricted and congruent with reported mood. Speech normal in rate and volume. No perceptual disturbance and no expressed intent to harm self or others.",
    "assessment": "Recurrence of situational insomnia against a background of anticipatory work anxiety. The adherence data is the useful finding: the intervention worked on the nights it was used and the patient had not connected the two.",
    "plan": "Make the adherence evidence explicit rather than instructing. Raise the target to six nights. Review sleep at next session and reconsider the formulation if unchanged."
  },
  "summary": "Follow-up addressing a one-week recurrence of middle-insomnia linked to anticipatory work anxiety. Partial adherence produced a measurable improvement the patient had not registered; the session focused on making that evidence visible and raising the target.",
  "patientBrief": "We talked about the sleep coming back this week, and about the review moving to Thursday being underneath it. The useful thing we found is that on the four nights you did the wind-down, you got back to sleep faster. You had not put those two together, and neither of us had said it out loud before today.",
  "patientSteps": [
    "Try the wind-down six nights this week rather than four.",
    "When you wake at three, write down in one line what the thought actually is. We are not going to argue with it yet."
  ],
  "patientNext": "Same time next week. If the sleep gets worse before then rather than better, message me and we will bring it forward.",
  "talkingPoints": [
    "The adherence data, said back to her rather than instructed",
    "Whether the review is the whole of it or a trigger for something older"
  ],
  "observations": "Noticeably lighter once the adherence pattern was named. Said she did not like needing it pointed out, which is worth returning to.",
  "impressions": "Adjustment-related insomnia, responsive to behavioural intervention. No indication of a primary mood disorder. Self-criticism on display in how she received a positive finding.",
  "recommendations": [
    "Continue behavioural sleep intervention, target six nights",
    "Revisit the self-critical response to progress if it recurs"
  ],
  "followUp": "Weekly. Reassess in three sessions and consider stepping down if sleep holds."
};

async function main() {
  const url = process.env.DATABASE_URL ?? "";
  const host = url.match(/@([^/:?]+)/)?.[1] ?? "(none)";

  console.log(`writing to ${host}\n`);

  if (host.includes(PRODUCTION_ENDPOINT)) {
    console.error("Refusing to run: that is production.");
    process.exit(1);
  }
  if (!host.includes(CAPTURE_ENDPOINT)) {
    console.error(
      `Refusing to run: this seed is for the capture branch only (${CAPTURE_ENDPOINT}).\n` +
        "A cast of invented therapists on any other branch will be mistaken for real state.",
    );
    process.exit(1);
  }

  const { pool, db } = connect();

  try {
    const hash = await hashPassword(PASSWORD);

    /*
     * 🔴 IT OWNS ITS OWN ROWS AND CLEARS THEM FIRST, so a second run is a clean run.
     *
     * The first version was not idempotent, and the first thing that happened was a partial run: it
     * created the sponsor, failed on the next statement, and then refused to start again because
     * `sponsor_users_email_unique` already held `hr@example.com`. A seed that can only be run once
     * is a seed that has to be preceded by a full purge every time, and 52.1 says the walkthrough and
     * the capture share ONE seeded run — which means re-running this after a fix must not require
     * re-purging and re-seeding everything else.
     *
     * Deleting by the cast's own markers rather than truncating, because `reset.ts` already did the
     * truncating and this must not undo the therapist, patient and session it seeded.
     */
    /*
     * 🔴 CHILDREN FIRST, AND 0082 IS WHY THE ORDER IS SPELLED OUT RATHER THAN GUESSED.
     *
     * The first version deleted `partners` before the `organizations` that reference it. Until 0082
     * that "worked", because the foreign key was ON DELETE SET NULL and silently nulled
     * `organizations.partner_id` — which then violated
     * `organizations_partner_billed_names_partner` and failed with an error naming a table this
     * script was not touching. With 0082's RESTRICT the same mistake fails immediately and says
     * exactly which constraint refused, which is the whole argument for RESTRICT over SET NULL.
     *
     * `organizations` therefore goes before `partners`, and `patients` before `people`.
     */
    for (const statement of [
      sql`DELETE FROM enrolments WHERE person_id IN (SELECT id FROM people WHERE last_name = 'Demo')`,
      sql`DELETE FROM ledger_entries WHERE ref_type = 'sponsor'`,
      sql`DELETE FROM sponsor_users WHERE email LIKE '%@example.com'`,
      /*
       * 🔴 A SESSION HOLDS A PATIENT DOWN, and the first content run proved it: deleting the cast
       * patients failed on `sessions_patient_id_patients_id_fk` because the walkthrough had left
       * sessions behind. The content this seed now writes makes that permanent rather than
       * accidental, so the whole subtree goes first, children before parents at every level.
       */
      sql`DELETE FROM transcript_segments WHERE session_id IN
            (SELECT s.id FROM sessions s JOIN patients p ON p.id = s.patient_id
              WHERE p.last_name = 'Demo')`,
      sql`DELETE FROM session_notes WHERE patient_id IN
            (SELECT id FROM patients WHERE last_name = 'Demo')`,
      sql`DELETE FROM assessment_responses WHERE assignment_id IN
            (SELECT a.id FROM assessment_assignments a JOIN patients p ON p.id = a.patient_id
              WHERE p.last_name = 'Demo')`,
      sql`DELETE FROM assessment_assignments WHERE patient_id IN
            (SELECT id FROM patients WHERE last_name = 'Demo')`,
      sql`DELETE FROM invoices WHERE session_id IN
            (SELECT s.id FROM sessions s JOIN patients p ON p.id = s.patient_id
              WHERE p.last_name = 'Demo')`,
      sql`DELETE FROM sessions WHERE patient_id IN
            (SELECT id FROM patients WHERE last_name = 'Demo')`,
      sql`DELETE FROM homework_items WHERE person_id IN
            (SELECT id FROM people WHERE last_name = 'Demo')`,
      sql`DELETE FROM journals WHERE person_id IN
            (SELECT id FROM people WHERE last_name = 'Demo')`,
      sql`DELETE FROM clinical_summaries WHERE person_id IN
            (SELECT id FROM people WHERE last_name = 'Demo')`,
      sql`DELETE FROM checkin_replies WHERE person_id IN
            (SELECT id FROM people WHERE last_name = 'Demo')`,
      sql`DELETE FROM checkins WHERE person_id IN
            (SELECT id FROM people WHERE last_name = 'Demo')`,
      sql`DELETE FROM patients WHERE last_name = 'Demo'`,
      /*
       * 🔴 The account's children before the account, and the account before the person.
       *
       * `history_grants` and `person_claims` both reference `patient_accounts`, and
       * `people.claimed_by_account_id` references it too — which is why `people` is cleared last
       * and the claim is unset before the account goes.
       */
      sql`DELETE FROM history_grants WHERE person_id IN (SELECT id FROM people WHERE last_name = 'Demo')`,
      sql`DELETE FROM person_claims WHERE person_id IN (SELECT id FROM people WHERE last_name = 'Demo')`,
      sql`UPDATE people SET claimed_at = NULL, claimed_by_account_id = NULL WHERE last_name = 'Demo'`,
      sql`DELETE FROM patient_accounts WHERE email LIKE '%.demo@example.com'`,
      sql`DELETE FROM people WHERE last_name = 'Demo'`,
      sql`DELETE FROM clinic_managers WHERE email LIKE '%@example.com'`,
      sql`DELETE FROM subscriptions WHERE organization_id IN
            (SELECT id FROM organizations WHERE slug IN ('demo-clinic', 'demo-health-clinicians'))`,
      /* Before the users they belong to, or the foreign key refuses the delete. */
      sql`DELETE FROM therapist_verifications WHERE user_id IN
            (SELECT id FROM users WHERE email LIKE '%@example.com' AND role = 'therapist')`,
      sql`DELETE FROM users WHERE email LIKE '%@example.com' AND role = 'therapist'`,
      /* 🔴 Before `partners`, per the block above. */
      sql`DELETE FROM organizations WHERE slug IN ('demo-clinic', 'demo-health-clinicians')`,
      sql`DELETE FROM partner_users WHERE email LIKE '%@example.com'`,
      sql`DELETE FROM partners WHERE slug = 'demo-health'`,
      sql`DELETE FROM eta_documents WHERE kind = 'credit_note' AND sponsor_id IN (SELECT id FROM sponsors WHERE name = 'Demo Holdings')`,
      sql`DELETE FROM eta_documents WHERE sponsor_id IN (SELECT id FROM sponsors WHERE name = 'Demo Holdings')`,
      sql`DELETE FROM pot_returns WHERE sponsor_id IN (SELECT id FROM sponsors WHERE name = 'Demo Holdings')`,
      sql`DELETE FROM sponsors WHERE name = 'Demo Holdings'`,
    ]) {
      await db.execute(statement);
    }

    /* The organisation `reset.ts` seeded, and the therapist under it. */
    const [{ id: soloOrgId }] = (
      await db.execute(sql`SELECT id FROM organizations WHERE slug = '24therapy' LIMIT 1`)
    ).rows as { id: string }[];

    const [{ id: therapistId }] = (
      await db.execute(
        sql`SELECT id FROM users WHERE email = ${CAST.therapist.email} LIMIT 1`,
      )
    ).rows as { id: string }[];

    console.log(`solo org ${soloOrgId}, therapist ${therapistId}`);

    /* 🔴 The admin door, openable. See the note on CAST.admin. */
    await db.execute(sql`
      UPDATE users SET password_hash = ${hash}, status = 'active'
       WHERE email = ${CAST.admin.email} AND role = 'super_admin'`);
    console.log(`admin: ${CAST.admin.email}`);

    /* ================================================================ */
    /*  The sponsor — 53. A company funding therapy nobody pays for.     */
    /* ================================================================ */

    const [sponsor] = (
      await db.execute(sql`
      INSERT INTO sponsors (name, kind, state, entity, currency, listed_publicly)
      VALUES ('Demo Holdings', 'company', 'active', 'us', 'usd', true)
      RETURNING id`)
    ).rows as { id: string }[];

    await db.execute(sql`
      INSERT INTO sponsor_users (sponsor_id, email, name, password_hash, role)
      VALUES (${sponsor.id}, ${CAST.sponsorUser.email}, ${CAST.sponsorUser.name}, ${hash}, 'admin')`);

    /*
     * 🔴 A funded pot, so the film can show a session the patient never pays for.
     *
     * The ledger sign convention: `sponsor_pot` is a LIABILITY, so a top-up is NEGATIVE and a spend
     * is positive. Getting this backwards is the sprint-53 bug the founder called the sharpest
     * finding in that report, and seeding it backwards would put a chart in a film showing every
     * deposit as expenditure.
     */
    await db.execute(sql`
      INSERT INTO ledger_entries (organization_id, account, amount_cents, currency, entity, txn_kind,
                                  ref_type, ref_id, txn_id, memo)
      VALUES (${soloOrgId}, 'sponsor_pot', -500000, 'usd', 'us', 'pot_topup',
              'sponsor', ${sponsor.id}, gen_random_uuid(), 'Demo Holdings opening balance')`);

    console.log(`sponsor: Demo Holdings, ${CAST.sponsorUser.email}`);

    /* ================================================================ */
    /*  The clinic — 54. An organisation with a manager and clinicians.  */
    /* ================================================================ */

    const [clinic] = (
      await db.execute(sql`
      INSERT INTO organizations (name, slug, kind, clinic_state, contact_name, contact_email,
                                 contact_phone)
      VALUES ('Demo Clinic', 'demo-clinic', 'clinic', 'active', ${CAST.clinicManager.name},
              ${CAST.clinicManager.email}, '+201300052100')
      RETURNING id`)
    ).rows as { id: string }[];

    await db.execute(sql`
      INSERT INTO subscriptions (organization_id, plan, status)
      VALUES (${clinic.id}, 'payg', 'active')`);

    await db.execute(sql`
      INSERT INTO clinic_managers (organization_id, email, name, password_hash, role)
      VALUES (${clinic.id}, ${CAST.clinicManager.email}, ${CAST.clinicManager.name}, ${hash},
              'admin')`);

    /* A verified clinician inside the clinic, so the clinic's schedule has a name on it. */
    const [clinicClinician] = (
      await db.execute(sql`
      INSERT INTO users (organization_id, email, first_name, last_name, role, verification_status,
                         password_hash, profile)
      VALUES (${clinic.id}, ${CAST.clinicClinician.email}, 'Tarek', 'Example', 'therapist',
              /* 🔴 C285: ignored by 0083's trigger and kept only so the column is named. The
                 approval below is what makes them verified. */
              'unverified', ${hash},
              '{"credentials":"MSc Clinical Psychology","licenseState":"EG","timezone":"Africa/Cairo"}'::jsonb)
      RETURNING id`)
    ).rows as { id: string }[];

    console.log(`clinic: Demo Clinic, ${CAST.clinicManager.email} + ${CAST.clinicClinician.email}`);

    /* ================================================================ */
    /*  The partner — 55. A platform whose clinician we can launch.      */
    /* ================================================================ */

    const [partner] = (
      await db.execute(sql`
      INSERT INTO partners (name, slug, state, contact_name, contact_email, contact_phone, intent)
      VALUES ('Demo Health Platform', 'demo-health', 'active', ${CAST.partnerUser.name},
              ${CAST.partnerUser.email}, '+201300052200',
              'Employment verification for our HR product, and session writeback from our own video.')
      RETURNING id`)
    ).rows as { id: string }[];

    await db.execute(sql`
      INSERT INTO partner_users (partner_id, email, name, password_hash, role)
      VALUES (${partner.id}, ${CAST.partnerUser.email}, ${CAST.partnerUser.name}, ${hash}, 'admin')`);

    /*
     * 🔴 A partner-billed organisation, which is what makes 55.9's launch possible.
     *
     * `launchClinician` requires `organizations.partner_id` with `billing_mode = 'partner_billed'`
     * — the association whose absence was the worst defect in sprint 55. Without it here, the
     * split-screen film's "a partner's call landing in a chart" cannot be walked at all.
     */
    const [partnerOrg] = (
      await db.execute(sql`
      INSERT INTO organizations (name, slug, kind, partner_id, billing_mode)
      VALUES ('Demo Health Clinicians', 'demo-health-clinicians', 'solo', ${partner.id},
              'partner_billed')
      RETURNING id`)
    ).rows as { id: string }[];

    await db.execute(sql`
      INSERT INTO subscriptions (organization_id, plan, status)
      VALUES (${partnerOrg.id}, 'payg', 'active')`);

    const [partnerClinician] = (
      await db.execute(sql`
      INSERT INTO users (organization_id, email, first_name, last_name, role, verification_status,
                         password_hash, profile)
      VALUES (${partnerOrg.id}, 'partner.clinician@example.com', 'Sara', 'Example', 'therapist',
              'unverified', ${hash},
              '{"credentials":"MD Psychiatry","licenseState":"EG","timezone":"Africa/Cairo"}'::jsonb)
      RETURNING id`)
    ).rows as { id: string }[];

    console.log(`partner: Demo Health Platform, ${CAST.partnerUser.email}`);

    /* ================================================================ */
    /*  🔴 The verifications, which are a SECOND record of the same fact */
    /* ================================================================ */

    /*
     * 🔴 `users.verification_status = 'verified'` IS NOT WHAT THE DATABASE CHECKS.
     *
     * The findings walk hit this trying to seed a history grant:
     *
     *     history_grants: a grant cannot be held by a clinician whose verification is not approved
     *
     * with all three clinicians already carrying `users.verification_status = 'verified'`. The
     * trigger reads `therapist_verifications.state = 'approved'`, a different table, and that table
     * was EMPTY. Two columns in two tables record one fact, and the seed set the one the screens
     * read while the one the database enforces stayed at its default.
     *
     * That is worth writing down rather than just fixing: it is the same shape as the comment-versus-
     * code family, moved into data. A row can say verified on every screen in the product while the
     * constraint that protects the clinical grant says it is not. The trigger is right and the
     * screens are the ones reading the softer column — which means the real question is what else
     * reads `users.verification_status` and believes it. `FINDINGS.md` carries it.
     *
     * 🔴 C285 CLOSED IT EVERYWHERE, AND THIS SELECT HAD TO CHANGE BECAUSE OF IT.
     *
     * 0083 makes `users.verification_status` derived: a trigger forces it to whatever
     * `therapist_verifications` says on every insert and update. So the first version of this
     * statement — `WHERE u.verification_status = 'verified'` — now selects NOTHING, because a
     * freshly inserted clinician derives to `unverified` until this very statement runs. A seed
     * that read the soft column was only ever working because the soft column was writable.
     *
     * It selects active clinicians instead and approves them, which is the honest shape: this is
     * the seed standing in for the administrator who reviews a licence.
     */
    await db.execute(sql`
      INSERT INTO therapist_verifications (user_id, organization_id, state, country, license_body,
                                           license_number, submitted_at, reviewed_at)
      SELECT u.id, u.organization_id, 'approved', 'EG', 'Egyptian Psychological Association',
             'DEMO-' || substr(u.id::text, 1, 8), now(), now()
        FROM users u
       WHERE u.role = 'therapist' AND u.status = 'active'
         AND NOT EXISTS (SELECT 1 FROM therapist_verifications v WHERE v.user_id = u.id)`);

    console.log("verifications: approved for every verified clinician");

    /* ================================================================ */
    /*  The patients, one per cross-portal flow (C268)                   */
    /* ================================================================ */

    for (const [who, orgId, clinicianId, forename] of [
      ["sponsoredPatient", soloOrgId, therapistId, "Layla"],
      ["clinicPatient", clinic.id, clinicClinician.id, "Youssef"],
      ["partnerPatient", partnerOrg.id, partnerClinician.id, "Mariam"],
    ] as const) {
      const person = CAST[who];

      const [created] = (
        await db.execute(sql`
        INSERT INTO patients (organization_id, therapist_id, first_name, last_name, phone, source)
        VALUES (${orgId}, ${clinicianId}, ${forename}, 'Demo', ${person.phone}, 'therapist')
        RETURNING id`)
      ).rows as { id: string }[];

      /*
       * 🔴 5.1 — every patient gets a PERSON, and the seed must do it explicitly.
       *
       * `ensurePersonForPatient` runs inside `createPatient`, which this does not use because a
       * seed has no `Actor`. A patient with no person row would leave the check-in channel and
       * Total View with nothing to join on, which would read as those features being broken in a
       * film rather than as a seed being incomplete.
       */
      await db.execute(sql`
        INSERT INTO people (first_name, last_name, phone, region)
        VALUES (${forename}, 'Demo', ${person.phone}, 'us')`);

      await db.execute(sql`
        UPDATE patients SET person_id = (SELECT id FROM people WHERE phone = ${person.phone})
         WHERE id = ${created.id}`);

      /*
       * 🔴 AND THE PERSON GETS AN ACCOUNT, AND CLAIMS THEIR OWN RECORD.
       *
       * Three writes, because sprint 6 made them three distinct facts and collapsing them would
       * seed a state the product cannot reach:
       *
       *   1. `patient_accounts` — somebody with a password. Email and phone both verified, because
       *      an unverified account is a different screen and this cast is not here to demonstrate
       *      the verification nag.
       *   2. `people.claimed_at` + `person_claims` — the moment the person took the record over.
       *      Without it the portal has an account attached to nothing and every list is empty.
       *   3. `history_grants` — `therapist_keeps_access = true`, which §3 makes an explicit grant
       *      rather than a default. 🔴 The default is OFF: absence of a grant is the revoked state.
       *      Seeding the claim without the grant would leave the clinician unable to see a record
       *      they are shown on screen in the very next flow, which in a split-screen cut would
       *      look like a bug in the product rather than a gap in the seed.
       */
      const [account] = (
        await db.execute(sql`
        INSERT INTO patient_accounts (person_id, email, password_hash, email_verified_at, phone,
                                      phone_verified_at, timezone)
        VALUES ((SELECT id FROM people WHERE phone = ${person.phone}), ${person.email}, ${hash},
                now(), ${person.phone}, now(), 'Africa/Cairo')
        RETURNING id`)
      ).rows as { id: string }[];

      await db.execute(sql`
        UPDATE people SET claimed_at = now(), claimed_by_account_id = ${account.id}
         WHERE phone = ${person.phone}`);

      await db.execute(sql`
        INSERT INTO person_claims (person_id, patient_account_id, route, status, verified_at,
                                   therapist_keeps_access)
        VALUES ((SELECT id FROM people WHERE phone = ${person.phone}), ${account.id},
                'match', 'verified', now(), true)`);

      await db.execute(sql`
        INSERT INTO history_grants (person_id, therapist_user_id, organization_id, status, shape,
                                    decided_at, updated_at)
        VALUES ((SELECT id FROM people WHERE phone = ${person.phone}), ${clinicianId}, ${orgId},
                'granted', 'open', now(), now())
        ON CONFLICT DO NOTHING`);

      console.log(`patient: ${person.name} (${person.phone}), signs in as ${person.email}`);
    }

    /*
     * 🔴 Layla is ENROLLED with the sponsor, which is what makes "a session the patient never pays
     * for" walkable. The identifier is hashed, as 53.20 requires: a stolen table is not a list of
     * work addresses.
     */
    await db.execute(sql`
      INSERT INTO enrolments (sponsor_id, person_id, identifier_hash, identifier_kind, state,
                             last_verified_at)
      VALUES (${sponsor.id},
              (SELECT id FROM people WHERE phone = ${CAST.sponsoredPatient.phone}),
              encode(sha256('capture:layla@example.com'::bytea), 'hex'),
              'domain_email', 'active', now())`);

    /* ================================================================ */
    /*  🔴 THE CONTENT. 52.1b — A CAST WITH NOTHING TO SHOW IS A FILM    */
    /*  ABOUT AN EMPTY PRODUCT.                                          */
    /* ================================================================ */

    /*
     * 🔴 WHY THIS SECTION EXISTS, IN ONE SENTENCE FROM THE FINDINGS PASS:
     *
     *   *The best-written sentences in the product are followed by "Nothing to do right now".*
     *
     * 52.3 photographed all six portals and found the design right, the structure right and the
     * writing exceptional — over empty states, on every screen. A cut of a well-written empty room
     * is a film about how little is in there, so the four cuts would have filmed the gap rather
     * than the product.
     *
     * ## 🔴 C225 GOVERNS THE CONTENT EXACTLY AS IT GOVERNS THE NAMES
     *
     * Every row below is invented. The discipline is harder here than it is for a name, because a
     * journal entry is a piece of writing about a person's inner life: it has to read as though a
     * real person could have written it **without being anybody**. So the material is deliberately
     * ordinary and specific-but-common — a review at work, waking at three, a sister's wedding —
     * rather than distinctive enough to belong to someone. Nothing here is drawn from any real
     * record, any real person, or anything the founder has described.
     *
     * 🔴 And nothing here is a crisis. A synthetic entry that tripped the risk path would seed a
     * `risk_assessments` row saying a person who does not exist is in danger, and put that sentence
     * in a marketing film. The journal is `risk_level: 'low'` and says so.
     *
     * ## One patient carries the story
     *
     * Layla Demo, in the solo practice, seen by Test Therapist and funded by Demo Holdings. The
     * other two keep their thinner records on purpose: a film needs one person whose history you
     * can follow and a list that does not look identical all the way down.
     */

    const layla = required(
      (
        await db.execute(sql`
          SELECT p.id AS patient_id, p.person_id, pa.id AS account_id
            FROM patients p
            JOIN patient_accounts pa ON pa.person_id = p.person_id
           WHERE p.phone = ${CAST.sponsoredPatient.phone}
           LIMIT 1`)
      ).rows[0] as { patient_id: string; person_id: string; account_id: string } | undefined,
      "Layla Demo's record and account",
    );

    /* ---------------------------------------------------------------- */
    /*  A session that actually happened: transcript, signed note, paid  */
    /* ---------------------------------------------------------------- */

    const [past] = (
      await db.execute(sql`
      INSERT INTO sessions (organization_id, therapist_id, patient_id, modality, status,
                            started_at, ended_at, duration_minutes, note_status, price_cents,
                            price_currency, payment_status, recording_consent, recording_consent_at,
                            transcript_language, session_type, feedback_token)
      VALUES (${soloOrgId}, ${therapistId}, ${layla.patient_id}, 'in_person', 'completed',
              now() - interval '8 days', now() - interval '8 days' + interval '50 minutes', 50,
              'approved', 45000, 'egp', 'paid', true, now() - interval '8 days',
              'en', 'standard', replace(gen_random_uuid()::text, '-', ''))
      RETURNING id`)
    ).rows as { id: string }[];

    /*
     * 🔴 A TRANSCRIPT THAT READS LIKE A ROOM, not like a demo script.
     *
     * Short, because the transcript panel in a film is read at a glance and a wall of text is a
     * wall. Ordinary, because this is the one artefact where invented clinical dialogue could be
     * mistaken for a real person's words if it were vivid enough to be somebody's.
     */
    const lines: [string, string][] = [
      ["therapist", "How has the sleep been since we last spoke?"],
      ["patient", "Better for about four nights. Then the review got moved up and it went again."],
      ["therapist", "Went again how? Getting off, or waking?"],
      ["patient", "Waking. Around three. And then it is just going over the same thing."],
      ["therapist", "You did the wind-down on the four nights it was better."],
      ["patient", "I suppose I did. I had not put those two together."],
    ];

    let seq = 0;
    for (const [speaker, text] of lines) {
      seq += 1;
      await db.execute(sql`
        INSERT INTO transcript_segments (session_id, organization_id, sequence, speaker, text,
                                         start_ms, end_ms)
        VALUES (${past.id}, ${soloOrgId}, ${seq}, ${speaker}, ${text},
                ${seq * 20000}, ${seq * 20000 + 9000})`);
    }

    /*
     * 🔴 The clinician's note is SIGNED and the patient's copy is RELEASED, because 47's whole
     * shape is that those are two decisions. A film that showed only the first would be showing
     * half of the sprint the founder called the honest record.
     */
    await db.execute(sql`
      INSERT INTO session_notes (session_id, organization_id, therapist_id, patient_id, content,
                                 status, approved_at, approved_by, language, provenance,
                                 patient_status, patient_approved_at, patient_approved_by)
      VALUES (${past.id}, ${soloOrgId}, ${therapistId}, ${layla.patient_id},
              ${JSON.stringify(NOTE)}::jsonb,
              'approved', now() - interval '8 days' + interval '55 minutes', ${therapistId},
              'en', 'transcript',
              'approved', now() - interval '8 days' + interval '56 minutes', ${therapistId})`);

    /* 🔴 A PAID INVOICE, so the billing screen is a receipt rather than a heading. */
    await db.execute(sql`
      INSERT INTO invoices (organization_id, kind, session_id, amount_cents, status, description,
                            issued_at, paid_at)
      VALUES (${soloOrgId}, 'session', ${past.id}, 45000, 'paid',
              'Session with Test Therapist, 50 minutes',
              now() - interval '8 days', now() - interval '8 days' + interval '1 hour')`);

    console.log("content: one completed session, transcript, signed note, paid invoice");

    /* ---------------------------------------------------------------- */
    /*  🔴 A summary with TWO clinicians' versions, which is the point   */
    /* ---------------------------------------------------------------- */

    /*
     * 🔴 "Every version stays, with the name of whoever wrote it, and nobody can take one back."
     *
     * That sentence is on the patient's summary screen and it is one of the best in the product,
     * and with one version it is a claim rather than a demonstration. Two clinicians, in order, is
     * the smallest cast that shows what it means: Tarek Example saw her first at the clinic, Test
     * Therapist added to it rather than over it.
     */
    await db.execute(sql`
      INSERT INTO clinical_summaries (person_id, version, body, approved_by_user_id,
                                      approved_by_name, approved_by_credentials,
                                      approved_by_license_body, approved_by_license_number,
                                      organization_id, approved_at)
      VALUES (${layla.person_id}, 1,
              ${`Referred after three months of disturbed sleep and low mood following a change of role. No prior contact with mental health services. Presentation is consistent with an adjustment difficulty rather than a primary mood disorder, and the sleep is the symptom she came for. Agreed a behavioural sleep intervention and six sessions to review.`},
              ${clinicClinician.id}, 'Tarek Example', 'MSc Clinical Psychology',
              'Egyptian Psychological Association', 'DEMO-CLINIC-1',
              ${clinic.id}, now() - interval '10 weeks')`);

    await db.execute(sql`
      INSERT INTO clinical_summaries (person_id, version, body, approved_by_user_id,
                                      approved_by_name, approved_by_credentials,
                                      approved_by_license_body, approved_by_license_number,
                                      organization_id, session_id, approved_at)
      VALUES (${layla.person_id}, 2,
              ${`Continuing work on sleep, now in the solo practice. The picture has narrowed since the first summary: mood has lifted with the role settling, and what remains is a recurrence of middle-insomnia tied to specific work events rather than a constant. The intervention is effective when used and the current work is adherence rather than technique. No change to formulation.`},
              ${therapistId}, 'Test Therapist', 'LCSW',
              'NY Office of the Professions', 'DEMO-SOLO-1',
              ${soloOrgId}, ${past.id}, now() - interval '8 days' + interval '57 minutes')`);

    console.log("content: a clinical summary with two clinicians' versions");

    /* ---------------------------------------------------------------- */
    /*  Homework in three states                                         */
    /* ---------------------------------------------------------------- */

    /*
     * 🔴 Three states because the screen has three and an empty one teaches nothing: done, open,
     * and skipped. The skipped one matters most for the film, because the screen says *"Do them or
     * do not, nobody is counting"* and a list where everything is ticked quietly contradicts it.
     */
    for (const [title, detail, status, days] of [
      [
        "The wind-down, six nights this week",
        "Same as before: screens down, lights low, and out of the bedroom if you are still awake after twenty minutes.",
        "done",
        6,
      ],
      [
        "Write down what the three o'clock thought actually is",
        "One line, on your phone, when it happens. We are not going to argue with it yet, only find out what it says.",
        "open",
        1,
      ],
      [
        "Ten minutes of walking before the review",
        "Optional. If the morning is already too full, leave it.",
        "skipped",
        4,
      ],
    ] as const) {
      await db.execute(sql`
        INSERT INTO homework_items (person_id, session_id, assigned_by_user_id, organization_id,
                                    title, detail, source, status, due_at, completed_at,
                                    patient_note)
        VALUES (${layla.person_id}, ${past.id}, ${therapistId}, ${soloOrgId},
                ${title}, ${detail}, 'therapist', ${status},
                now() + interval '${sql.raw(String(7 - days))} days',
                ${status === "done" ? sql`now() - interval '3 days'` : sql`NULL`},
                ${status === "done" ? "Did it four nights. The other three I forgot." : null})`);
    }

    console.log("content: homework in three states");

    /* ---------------------------------------------------------------- */
    /*  A journal entry                                                  */
    /* ---------------------------------------------------------------- */

    /*
     * 🔴 THE HARDEST ROW IN THIS FILE TO WRITE HONESTLY.
     *
     * C225 says synthetic, and a journal is the one artefact where "synthetic" and "reads like a
     * person" pull hardest against each other. The rule applied here: ordinary material, specific
     * enough to be believable, common enough to belong to nobody. A moved deadline and a sister's
     * wedding are true of thousands of people and identify none of them.
     *
     * `risk_level: 'low'`, explicitly, and nothing in the text that would route to the crisis path.
     * A synthetic entry that raised a risk assessment would put "this person may be in danger" in a
     * database and then in a promotional film, about somebody who does not exist.
     */
    await db.execute(sql`
      INSERT INTO journals (person_id, account_id, source, body, risk_level, created_at)
      VALUES (${layla.person_id}, ${layla.account_id}, 'typed',
              ${`Awake at three again. The review moved to Thursday and I think I have been carrying that around since Monday without noticing.\n\nWhat is strange is that I did the wind-down on the nights it worked and did not connect it. I only saw it when he said it back to me. I do not love that about myself, that I need somebody else to point at the obvious thing.\n\nMy sister's wedding is in three weeks and I would like to be sleeping by then. Not for any dramatic reason. I would just like to enjoy it.`},
              'low', now() - interval '2 days')`);

    console.log("content: a journal entry");

    /* ---------------------------------------------------------------- */
    /*  An assessment result, with its per-answer timings                */
    /* ---------------------------------------------------------------- */

    /*
     * 🔴 The instruments are seeded and published through the PRODUCT'S OWN functions, not by an
     * INSERT here. `publishInstrument` refuses a licensed instrument and refuses a translated one
     * nobody has read, and a seed that wrote `published_at` directly would be the one path around
     * both — which is exactly the shape of defect this sprint keeps finding.
     */
    const { seedInstruments, publishInstrument } = await import("../lib/data/assessments");
    const seeded = await seedInstruments();

    const [adminUser] = (
      await db.execute(
        sql`SELECT id FROM users WHERE email = ${CAST.admin.email} LIMIT 1`,
      )
    ).rows as { id: string }[];

    /* A named person read the Arabic, which is what 56.11 requires before publication. */
    await db.execute(sql`
      UPDATE instruments
         SET translation_reviewed_by = ${adminUser.id}, translation_reviewed_at = now()
       WHERE translation_reviewed_by IS NULL`);

    const instrumentRows = (
      await db.execute(sql`SELECT id, key FROM instruments`)
    ).rows as { id: string; key: string }[];

    for (const row of instrumentRows) {
      await publishInstrument({
        id: row.id,
        actor: { userId: adminUser.id, role: "super_admin", organizationId: soloOrgId } as never,
      });
    }

    const phq9 = required(
      instrumentRows.find((row) => row.key === "phq9"),
      "the PHQ-9 instrument",
    );

    const [assignment] = (
      await db.execute(sql`
      INSERT INTO assessment_assignments (instrument_id, patient_id, organization_id,
                                          assigned_by_user_id, session_id, mode, status, score,
                                          instrument_version, started_at, completed_at)
      VALUES (${phq9.id}, ${layla.patient_id}, ${soloOrgId}, ${therapistId}, ${past.id},
              'homework', 'completed', 11, 1,
              now() - interval '6 days', now() - interval '6 days' + interval '4 minutes')
      RETURNING id`)
    ).rows as { id: string }[];

    /*
     * 🔴 PER-ANSWER TIMINGS, which is the detail the founder asked for by name and the one thing
     * here that could not be faked convincingly by hand.
     *
     * `answer_ms` is how long each question took. The pattern is the point: the sleep item and the
     * concentration item take three and four times as long as the rest, because those are the ones
     * she had to think about. Uniform timings would be a screenshot of a spreadsheet. This is what
     * somebody answering honestly on a phone looks like.
     */
    const answers: [string, number, number][] = [
      ["interest", 1, 4200],
      ["mood", 2, 5100],
      ["sleep", 3, 16400],
      ["energy", 2, 3800],
      ["appetite", 0, 2900],
      ["failure", 1, 11200],
      ["concentration", 2, 14800],
      ["psychomotor", 0, 3100],
      ["selfharm", 0, 6700],
    ];

    for (const [key, value, ms] of answers) {
      await db.execute(sql`
        INSERT INTO assessment_responses (assignment_id, question_key, value, answer_ms,
                                          answered_at)
        VALUES (${assignment.id}, ${key}, ${value}, ${ms}, now() - interval '6 days')`);
    }

    console.log(
      `content: PHQ-9 completed, score 11, nine answers with timings (${seeded.inserted} instruments seeded)`,
    );

    /* ---------------------------------------------------------------- */
    /*  A check-in, and a reply                                          */
    /* ---------------------------------------------------------------- */

    /*
     * 🔴 44.2 — A CHECK-IN ASKS, IT NEVER INTERPRETS, and the reply seeded here is the ordinary
     * kind precisely so the film shows the ordinary case. `crisis_alert_raised` is false and there
     * is no `risk_assessments` row, because the crisis path is a thing to demonstrate in a verifier
     * and not a thing to stage for a camera.
     */
    const [checkin] = (
      await db.execute(sql`
      INSERT INTO checkins (person_id, channel, body, locale, sent_at, delivered)
      VALUES (${layla.person_id}, 'whatsapp',
              'How have you been since your last session? No need to reply if you would rather not.',
              'en', now() - interval '4 days', true)
      RETURNING id`)
    ).rows as { id: string }[];

    await db.execute(sql`
      INSERT INTO checkin_replies (checkin_id, person_id, body, crisis_alert_raised, received_at)
      VALUES (${checkin.id}, ${layla.person_id},
              'Mixed. Sleeping better at the start of the week. Thanks for asking.',
              false, now() - interval '4 days' + interval '2 hours')`);

    console.log("content: a check-in and an ordinary reply");

    console.log("\nDone. Six principals, one seeded run.");
    console.log(`\npassword for every synthetic account: ${PASSWORD}`);
  } finally {
    await pool.end();
  }
}

void main();
